# Generated by Django 6.0.7 on 2026-07-30 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('withdrawn', 'Retirada')], default='active', editable=False, max_length=10)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('first_published_at', models.DateTimeField()),
                ('last_published_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='courses.course')),
                ('first_published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_publications_first_published', to=settings.AUTH_USER_MODEL)),
                ('last_published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_publications_last_published', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_publications_withdrawn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(editable=False)),
                ('schema_version', models.PositiveIntegerField(editable=False)),
                ('snapshot', models.JSONField(editable=False)),
                ('snapshot_digest', models.CharField(editable=False, max_length=64)),
                ('snapshot_size_bytes', models.PositiveIntegerField(editable=False)),
                ('title', models.CharField(editable=False, max_length=200)),
                ('summary', models.TextField(editable=False, max_length=1200)),
                ('language_code', models.CharField(editable=False, max_length=12)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('module_count', models.PositiveIntegerField(editable=False)),
                ('unit_count', models.PositiveIntegerField(editable=False)),
                ('word_count', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_releases_created', to=settings.AUTH_USER_MODEL)),
                ('previous_release', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_releases', to='publishing.courserelease')),
                ('source_revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release', to='courses.courserevision')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CoursePublicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('release_published', 'Release publicado'), ('publication_withdrawn', 'Publicación retirada'), ('draft_created_from_release', 'Draft creado desde release')], max_length=32)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_publication_events', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_events', to='courses.course')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='publishing.coursepublication')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_events', to='courses.courserevision')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='publishing.courserelease')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='coursepublication',
            name='current_release',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_publications', to='publishing.courserelease'),
        ),
        migrations.AddIndex(
            model_name='courserelease',
            index=models.Index(fields=['course', 'created_at'], name='pub_rel_course_created_ix'),
        ),
        migrations.AddIndex(
            model_name='courserelease',
            index=models.Index(fields=['snapshot_digest'], name='publishing_rel_digest_ix'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='publishing_release_course_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='publishing_release_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gt', 0)), name='publishing_release_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_size_bytes__gt', 0)), name='publishing_release_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_digest__regex', '^[0-9a-f]{64}$')), name='publishing_release_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_minutes__isnull', True), ('estimated_duration_minutes__gt', 0), _connector='OR'), name='publishing_release_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.CheckConstraint(condition=models.Q(('previous_release__isnull', True), models.Q(('previous_release', models.F('id')), _negated=True), _connector='OR'), name='publishing_release_not_self_previous'),
        ),
        migrations.AddIndex(
            model_name='coursepublicationevent',
            index=models.Index(fields=['course', 'created_at'], name='pub_evt_course_created_ix'),
        ),
        migrations.AddIndex(
            model_name='coursepublicationevent',
            index=models.Index(fields=['publication', 'created_at'], name='publishing_evt_pub_created_ix'),
        ),
        migrations.AddIndex(
            model_name='coursepublicationevent',
            index=models.Index(fields=['release', 'created_at'], name='publishing_evt_rel_created_ix'),
        ),
        migrations.AddConstraint(
            model_name='coursepublicationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'release_published'), ('release__isnull', False)), models.Q(('event_type', 'publication_withdrawn'), ('release__isnull', False), models.Q(('note', ''), _negated=True)), models.Q(('event_type', 'draft_created_from_release'), ('release__isnull', False), ('revision__isnull', False)), _connector='OR'), name='publishing_event_payload'),
        ),
        migrations.AddIndex(
            model_name='coursepublication',
            index=models.Index(fields=['status'], name='publishing_pub_status_ix'),
        ),
        migrations.AddIndex(
            model_name='coursepublication',
            index=models.Index(fields=['current_release'], name='publishing_pub_current_ix'),
        ),
        migrations.AddConstraint(
            model_name='coursepublication',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='publishing_publication_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursepublication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), ('withdrawal_note', ''), ('withdrawn_at__isnull', True), ('withdrawn_by__isnull', True)), models.Q(('status', 'withdrawn'), ('withdrawn_at__isnull', False), ('withdrawn_by__isnull', False), models.Q(('withdrawal_note', ''), _negated=True)), _connector='OR'), name='publishing_publication_lifecycle'),
        ),
    ]
