# Generated by Django 6.0.7 on 2026-07-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION publishing_reject_immutable_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'immutable publishing record: % is not allowed on %',
        TG_OP, TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER publishing_release_reject_update
BEFORE UPDATE ON publishing_courserelease
FOR EACH ROW EXECUTE FUNCTION publishing_reject_immutable_change();

CREATE TRIGGER publishing_release_reject_delete
BEFORE DELETE ON publishing_courserelease
FOR EACH ROW EXECUTE FUNCTION publishing_reject_immutable_change();

CREATE TRIGGER publishing_event_reject_update
BEFORE UPDATE ON publishing_coursepublicationevent
FOR EACH ROW EXECUTE FUNCTION publishing_reject_immutable_change();

CREATE TRIGGER publishing_event_reject_delete
BEFORE DELETE ON publishing_coursepublicationevent
FOR EACH ROW EXECUTE FUNCTION publishing_reject_immutable_change();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS publishing_event_reject_delete
    ON publishing_coursepublicationevent;
DROP TRIGGER IF EXISTS publishing_event_reject_update
    ON publishing_coursepublicationevent;
DROP TRIGGER IF EXISTS publishing_release_reject_delete
    ON publishing_courserelease;
DROP TRIGGER IF EXISTS publishing_release_reject_update
    ON publishing_courserelease;
DROP FUNCTION IF EXISTS publishing_reject_immutable_change();
""",
        ),
    ]
