# Generated by Django 6.0.7 on 2026-07-29 07:01

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='org_slug_ix')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim(models.F('name'))), models.Q(('name', ''), _negated=True)), name='organizations_name_trimmed_nonempty'), models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='organizations_slug_lowercase')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('revoked', 'Revocada')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_membership_status_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('administrator', 'Administrador'), ('author', 'Autor'), ('reviewer', 'Revisor'), ('instructor', 'Docente'), ('learner', 'Estudiante')], max_length=32)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.membership')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_roles_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['membership', 'role'], name='org_role_member_role_ix')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('membership', 'role'), name='organizations_one_active_role_assignment'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('assigned_at')), _connector='OR'), name='organizations_role_revoked_after_assigned')],
            },
        ),
        migrations.CreateModel(
            name='MembershipEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('membership_created', 'Membresía creada'), ('membership_suspended', 'Membresía suspendida'), ('membership_reactivated', 'Membresía reactivada'), ('membership_revoked', 'Membresía revocada'), ('role_assigned', 'Rol asignado'), ('role_revoked', 'Rol revocado')], max_length=32)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Propietario'), ('administrator', 'Administrador'), ('author', 'Autor'), ('reviewer', 'Revisor'), ('instructor', 'Docente'), ('learner', 'Estudiante')], default='', max_length=32)),
                ('previous_status', models.CharField(blank=True, choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('revoked', 'Revocada')], default='', max_length=16)),
                ('new_status', models.CharField(blank=True, choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('revoked', 'Revocada')], default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_membership_events', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_events', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'created_at'], name='org_event_org_created_ix'), models.Index(fields=['membership', 'created_at'], name='org_event_member_created_ix')],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'status'], name='org_member_state_ix'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='org_member_user_ix'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'revoked'), _negated=True), fields=('organization', 'user'), name='organizations_one_current_membership'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active'), ('suspended_at__isnull', True)), models.Q(('revoked_at__isnull', True), ('status', 'suspended'), ('suspended_at__isnull', False)), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='organizations_membership_state_timestamps'),
        ),
    ]
