# Generated by Django 6.0.7 on 2026-08-01 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipevent',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='membershipevent',
            name='event_type',
            field=models.CharField(choices=[('membership_created', 'Membresía creada'), ('membership_suspended', 'Membresía suspendida'), ('membership_reactivated', 'Membresía reactivada'), ('membership_revoked', 'Membresía revocada'), ('role_assigned', 'Rol asignado'), ('role_revoked', 'Rol revocado'), ('invitation_created', 'Invitación creada'), ('invitation_resent', 'Invitación reenviada'), ('invitation_revoked', 'Invitación revocada'), ('invitation_accepted', 'Invitación aceptada'), ('join_requested', 'Solicitud de ingreso creada'), ('join_approved', 'Solicitud de ingreso aprobada'), ('join_rejected', 'Solicitud de ingreso rechazada'), ('managed_account_created', 'Cuenta administrada creada'), ('managed_account_activated', 'Cuenta administrada activada'), ('profile_updated', 'Perfil institucional actualizado'), ('roles_replaced', 'Roles sustituidos'), ('sessions_revoked', 'Sesiones revocadas'), ('membership_settings_updated', 'Configuración de membresías actualizada')], max_length=32),
        ),
        migrations.AlterField(
            model_name='membershipevent',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.membership'),
        ),
        migrations.CreateModel(
            name='OrganizationMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(blank=True, max_length=80)),
                ('institutional_id', models.CharField(blank=True, max_length=120)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('locale', models.CharField(default='es', max_length=16)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('administrative_notes', models.TextField(blank=True, max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='institutional_profile', to='organizations.membership')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invited_roles', models.JSONField(default=list)),
                ('invitation_type', models.CharField(choices=[('existing_user', 'Usuario existente'), ('new_user', 'Usuario nuevo'), ('managed_account', 'Cuenta administrada')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('revoked', 'Revocada'), ('expired', 'Expirada')], default='pending', max_length=16)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('given_name', models.CharField(blank=True, max_length=150)),
                ('family_name', models.CharField(blank=True, max_length=150)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('member_type', models.CharField(blank=True, max_length=80)),
                ('institutional_id', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('locale', models.CharField(default='es', max_length=16)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existing_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_invitations', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'expires_at'], name='org_invite_due_ix'), models.Index(fields=['organization', 'email'], name='org_invite_email_ix')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='organizations_one_pending_invitation_email'), models.CheckConstraint(condition=models.Q(('accepted_at__isnull', True), ('status', 'accepted'), _connector='OR'), name='organizations_invitation_acceptance_state'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('status', 'revoked'), _connector='OR'), name='organizations_invitation_revocation_state')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='join_requests', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_join_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='org_join_status_ix')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user'), name='organizations_one_pending_join_request')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembershipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_join_enabled', models.BooleanField(default=False)),
                ('join_requires_approval', models.BooleanField(default=True)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list)),
                ('default_role', models.CharField(choices=[('owner', 'Propietario'), ('administrator', 'Administrador'), ('author', 'Autor'), ('reviewer', 'Revisor'), ('instructor', 'Docente'), ('learner', 'Estudiante')], default='learner', max_length=32)),
                ('invitation_expiry_hours', models.PositiveIntegerField(default=168)),
                ('allow_admin_managed_accounts', models.BooleanField(default=True)),
                ('allow_bulk_invitations', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership_settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_membership_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('invitation_expiry_hours__gte', 1), ('invitation_expiry_hours__lte', 720)), name='organizations_invitation_expiry_bounded'), models.CheckConstraint(condition=models.Q(('default_role', 'owner'), _negated=True), name='organizations_default_role_not_owner')],
            },
        ),
    ]
