# Generated by Django 6.0.7 on 2026-08-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_legacy_profiles_and_event_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipevent',
            name='event_type',
            field=models.CharField(choices=[('membership_created', 'Membresía creada'), ('membership_suspended', 'Membresía suspendida'), ('membership_reactivated', 'Membresía reactivada'), ('membership_revoked', 'Membresía revocada'), ('role_assigned', 'Rol asignado'), ('role_revoked', 'Rol revocado'), ('invitation_created', 'Invitación creada'), ('invitation_updated', 'Invitación actualizada'), ('invitation_resent', 'Invitación reenviada'), ('invitation_revoked', 'Invitación revocada'), ('invitation_accepted', 'Invitación aceptada'), ('join_requested', 'Solicitud de ingreso creada'), ('join_approved', 'Solicitud de ingreso aprobada'), ('join_rejected', 'Solicitud de ingreso rechazada'), ('managed_account_created', 'Cuenta administrada creada'), ('managed_account_activated', 'Cuenta administrada activada'), ('profile_updated', 'Perfil institucional actualizado'), ('roles_replaced', 'Roles sustituidos'), ('sessions_revoked', 'Sesiones revocadas'), ('membership_settings_updated', 'Configuración de membresías actualizada')], max_length=32),
        ),
    ]
