# Generated by Django 6.0.7 on 2026-08-01 10:01

from django.db import migrations, models


def normalize_existing_profiles(apps, schema_editor):
    Profile = apps.get_model("organizations", "OrganizationMemberProfile")
    Invitation = apps.get_model("organizations", "MembershipInvitation")
    mapping = {
        "estudiante": "learner",
        "student": "learner",
        "docente": "instructor",
        "profesor": "instructor",
        "teacher": "instructor",
        "acudiente": "guardian",
        "administrativo": "administrative",
    }
    for profile in Profile.objects.select_related("membership__user").iterator():
        user = profile.membership.user
        profile.first_name = user.first_name.strip()
        profile.first_surname = user.last_name.strip()
        raw_type = profile.member_type.strip().lower()
        profile.member_type = mapping.get(raw_type, raw_type if raw_type in mapping.values() else "")
        profile.save(update_fields=("first_name", "first_surname", "member_type"))
    for invitation in Invitation.objects.iterator():
        raw_type = invitation.member_type.strip().lower()
        invitation.member_type = mapping.get(
            raw_type, raw_type if raw_type in mapping.values() else ""
        )
        invitation.save(update_fields=("member_type",))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_membershipevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinvitation',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='department_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='document_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='document_type',
            field=models.CharField(blank=True, choices=[('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PPT', 'Permiso por protección temporal'), ('PA', 'Pasaporte'), ('DE', 'Documento extranjero'), ('NONE', 'Sin documento registrado')], max_length=8),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='education_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='education_level',
            field=models.CharField(blank=True, choices=[('preschool', 'Preescolar'), ('grade_1', '1.º'), ('grade_2', '2.º'), ('grade_3', '3.º'), ('grade_4', '4.º'), ('grade_5', '5.º'), ('grade_6', '6.º'), ('grade_7', '7.º'), ('grade_8', '8.º'), ('grade_9', '9.º'), ('grade_10', '10.º'), ('grade_11', '11.º'), ('technical', 'Técnico profesional'), ('technologist', 'Tecnólogo'), ('undergraduate', 'Pregrado universitario'), ('specialization', 'Especialización'), ('masters', 'Maestría'), ('doctorate', 'Doctorado'), ('not_applicable', 'No aplica')], max_length=32),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('preschool', 'Preescolar'), ('school', 'Colegio'), ('technical', 'Institución técnica o tecnológica'), ('university', 'Universidad'), ('graduated', 'Graduado'), ('not_studying', 'Actualmente no estudia'), ('other', 'Otra situación')], max_length=24),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Femenino'), ('male', 'Masculino'), ('non_binary', 'No binario'), ('other', 'Otro'), ('prefer_not_to_say', 'Prefiero no responder')], max_length=24),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='municipality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='registration_reason',
            field=models.CharField(blank=True, choices=[('course', 'Tomar un curso'), ('school_support', 'Refuerzo escolar'), ('exam_preparation', 'Preparación para una evaluación'), ('professional_development', 'Formación profesional'), ('teaching', 'Enseñar o acompañar estudiantes'), ('institutional', 'Vinculación institucional'), ('other', 'Otro motivo')], max_length=32),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='registration_reason_detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='second_family_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='socioeconomic_stratum',
            field=models.CharField(blank=True, choices=[('not_reported', 'Prefiere no informar'), ('rural', 'Rural o sin estratificación'), ('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=16),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='department_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='document_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PPT', 'Permiso por protección temporal'), ('PA', 'Pasaporte'), ('DE', 'Documento extranjero'), ('NONE', 'Sin documento registrado')], max_length=8),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='education_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('preschool', 'Preescolar'), ('grade_1', '1.º'), ('grade_2', '2.º'), ('grade_3', '3.º'), ('grade_4', '4.º'), ('grade_5', '5.º'), ('grade_6', '6.º'), ('grade_7', '7.º'), ('grade_8', '8.º'), ('grade_9', '9.º'), ('grade_10', '10.º'), ('grade_11', '11.º'), ('technical', 'Técnico profesional'), ('technologist', 'Tecnólogo'), ('undergraduate', 'Pregrado universitario'), ('specialization', 'Especialización'), ('masters', 'Maestría'), ('doctorate', 'Doctorado'), ('not_applicable', 'No aplica')], max_length=32),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='education_stage',
            field=models.CharField(blank=True, choices=[('preschool', 'Preescolar'), ('school', 'Colegio'), ('technical', 'Institución técnica o tecnológica'), ('university', 'Universidad'), ('graduated', 'Graduado'), ('not_studying', 'Actualmente no estudia'), ('other', 'Otra situación')], max_length=24),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='first_surname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Femenino'), ('male', 'Masculino'), ('non_binary', 'No binario'), ('other', 'Otro'), ('prefer_not_to_say', 'Prefiero no responder')], max_length=24),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='registration_reason',
            field=models.CharField(blank=True, choices=[('course', 'Tomar un curso'), ('school_support', 'Refuerzo escolar'), ('exam_preparation', 'Preparación para una evaluación'), ('professional_development', 'Formación profesional'), ('teaching', 'Enseñar o acompañar estudiantes'), ('institutional', 'Vinculación institucional'), ('other', 'Otro motivo')], max_length=32),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='registration_reason_detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='second_surname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='socioeconomic_stratum',
            field=models.CharField(blank=True, choices=[('not_reported', 'Prefiere no informar'), ('rural', 'Rural o sin estratificación'), ('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=16),
        ),
        migrations.AddField(
            model_name='organizationmemberprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(normalize_existing_profiles, noop_reverse),
        migrations.AlterField(
            model_name='membershipinvitation',
            name='member_type',
            field=models.CharField(blank=True, choices=[('learner', 'Estudiante'), ('instructor', 'Docente'), ('guardian', 'Acudiente'), ('administrative', 'Personal administrativo'), ('support', 'Personal de apoyo'), ('other', 'Otro')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationmemberprofile',
            name='member_type',
            field=models.CharField(blank=True, choices=[('learner', 'Estudiante'), ('instructor', 'Docente'), ('guardian', 'Acudiente'), ('administrative', 'Personal administrativo'), ('support', 'Personal de apoyo'), ('other', 'Otro')], max_length=32),
        ),
    ]
