# Generated by Django 6.0.7 on 2026-08-02 01:38

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_existing_organizations(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.filter(activated_at__isnull=True).update(
        activated_at=F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_membershipevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending_activation', 'Pendiente de activación'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('closed', 'Cerrada')], default='active', max_length=24),
        ),
        migrations.AlterField(
            model_name='membershipinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('existing_user', 'Usuario existente'), ('new_user', 'Usuario nuevo'), ('managed_account', 'Cuenta administrada'), ('initial_owner', 'Propietario inicial')], max_length=24),
        ),
        migrations.RunPython(
            backfill_existing_organizations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='organization',
            name='activated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('status', 'pending_activation')), models.Q(('activated_at__isnull', False), ('status__in', ('active', 'suspended', 'closed'))), _connector='OR'), name='organizations_activation_lifecycle'),
        ),
    ]
