# Generated by Django 6.0.7 on 2026-07-29 18:13

import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('summary', models.TextField(max_length=1200)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('language_code', models.CharField(default='es', max_length=12)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('authoring_status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobada')], default='draft', editable=False, max_length=24)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_revisions', to='courses.courserevision')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_revision_status_changes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_revisions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_modules_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_modules_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_modules_updated', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='courses.courserevision')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CourseRevisionLearningObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_objective_alignments_created', to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_revision_alignments', to='catalog.learningobjective')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_alignments', to='courses.courserevision')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CourseRevisionSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alignment_type', models.CharField(choices=[('primary', 'Principal'), ('supporting', 'Complementaria')], max_length=12)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_subject_alignments_created', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_alignments', to='courses.courserevision')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_revision_alignments', to='catalog.subject')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CourseRevisionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobada')], max_length=24, null=True)),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobada')], max_length=24)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_revision_transitions', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='courses.courserevision')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=1200)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_units_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_units_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='courses.coursemodule')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_units_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CourseUnitLearningObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_unit_objective_alignments_created', to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_unit_alignments', to='catalog.learningobjective')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_alignments', to='courses.courseunit')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CourseUnitTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_unit_topic_alignments_created', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_unit_alignments', to='catalog.topic')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_alignments', to='courses.courseunit')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'status'], name='course_org_status_ix'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='course_created_ix'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('slug'), name='courses_course_org_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='courses_course_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived')), _connector='OR'), name='courses_course_archive_state'),
        ),
        migrations.AddIndex(
            model_name='courserevision',
            index=models.Index(fields=['course', 'authoring_status'], name='revision_course_state_ix'),
        ),
        migrations.AddIndex(
            model_name='courserevision',
            index=models.Index(fields=['updated_at'], name='revision_updated_ix'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='courses_revision_course_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.UniqueConstraint(condition=models.Q(('authoring_status__in', ['changes_requested', 'draft', 'in_review'])), fields=('course',), name='courses_revision_one_open'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='courses_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='courses_revision_lock_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_minutes__isnull', True), ('estimated_duration_minutes__gt', 0), _connector='OR'), name='courses_revision_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.CheckConstraint(condition=models.Q(('based_on_revision__isnull', True), models.Q(('based_on_revision', models.F('id')), _negated=True), _connector='OR'), name='courses_revision_not_self_based'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.CheckConstraint(condition=models.Q(('title', django.db.models.functions.text.Trim(models.F('title'))), models.Q(('title', ''), _negated=True)), name='courses_revision_title_trimmed'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['revision', 'status', 'position'], name='module_revision_state_pos_ix'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('revision', 'position'), name='courses_module_revision_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('position__gt', 0), ('position__isnull', False), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('position__isnull', True), ('status', 'archived')), _connector='OR'), name='courses_module_state_position'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionlearningobjective',
            constraint=models.UniqueConstraint(fields=('revision', 'learning_objective'), name='courses_revision_objective_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionlearningobjective',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='courses_revision_objective_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionlearningobjective',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_revision_objective_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionsubject',
            constraint=models.UniqueConstraint(fields=('revision', 'subject'), name='courses_revision_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionsubject',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='courses_revision_subject_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('alignment_type', 'primary')), fields=('revision',), name='courses_revision_one_primary_subject'),
        ),
        migrations.AddConstraint(
            model_name='courserevisionsubject',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_revision_subject_position_positive'),
        ),
        migrations.AddIndex(
            model_name='courserevisiontransition',
            index=models.Index(fields=['revision', 'created_at'], name='transition_revision_created_ix'),
        ),
        migrations.AddIndex(
            model_name='courseunit',
            index=models.Index(fields=['module', 'status', 'position'], name='unit_module_state_pos_ix'),
        ),
        migrations.AddConstraint(
            model_name='courseunit',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('module', 'position'), name='courses_unit_module_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('position__gt', 0), ('position__isnull', False), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('position__isnull', True), ('status', 'archived')), _connector='OR'), name='courses_unit_state_position'),
        ),
        migrations.AddConstraint(
            model_name='courseunit',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_minutes__isnull', True), ('estimated_duration_minutes__gt', 0), _connector='OR'), name='courses_unit_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseunitlearningobjective',
            constraint=models.UniqueConstraint(fields=('unit', 'learning_objective'), name='courses_unit_objective_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseunitlearningobjective',
            constraint=models.UniqueConstraint(fields=('unit', 'position'), name='courses_unit_objective_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseunitlearningobjective',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_unit_objective_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseunittopic',
            constraint=models.UniqueConstraint(fields=('unit', 'topic'), name='courses_unit_topic_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseunittopic',
            constraint=models.UniqueConstraint(fields=('unit', 'position'), name='courses_unit_topic_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseunittopic',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_unit_topic_position_positive'),
        ),
    ]
