# Generated by Django 6.0.7 on 2026-08-02 01:39

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_lesson_activities(apps, schema_editor):
    Unit = apps.get_model('courses', 'CourseUnit')
    UnitObjective = apps.get_model('courses', 'CourseUnitLearningObjective')
    Activity = apps.get_model('courses', 'CourseActivity')
    ActivityObjective = apps.get_model('courses', 'CourseActivityLearningObjective')
    CompletionPolicy = apps.get_model('courses', 'CourseCompletionPolicy')
    Revision = apps.get_model('courses', 'CourseRevision')

    for unit in Unit.objects.all().iterator():
        activity = Activity.objects.create(
            id=unit.id,
            module_id=unit.module_id,
            activity_type='lesson',
            lesson_unit_id=unit.id,
            title=unit.title,
            summary=unit.summary,
            estimated_duration_minutes=unit.estimated_duration_minutes,
            required=True,
            completion_method='view',
            status=unit.status,
            position=unit.position,
            created_by_id=unit.created_by_id,
            updated_by_id=unit.updated_by_id,
            archived_by_id=unit.archived_by_id,
            archived_at=unit.archived_at,
        )
        Activity.objects.filter(pk=activity.pk).update(
            created_at=unit.created_at,
            updated_at=unit.updated_at,
        )
        for alignment in UnitObjective.objects.filter(unit_id=unit.id).iterator():
            ActivityObjective.objects.create(
                id=alignment.id,
                activity_id=activity.id,
                learning_objective_id=alignment.learning_objective_id,
                position=alignment.position,
                created_by_id=alignment.created_by_id,
            )

    for revision in Revision.objects.all().iterator():
        CompletionPolicy.objects.create(
            revision_id=revision.id,
            require_required_activities=True,
            updated_by_id=revision.updated_by_id,
        )


def reverse_lesson_activities(apps, schema_editor):
    apps.get_model('courses', 'CourseCompletionPolicy').objects.all().delete()
    apps.get_model('courses', 'CourseActivityLearningObjective').objects.all().delete()
    apps.get_model('courses', 'CourseActivity').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('lesson', 'Lección'), ('live_class', 'Clase en vivo'), ('assessment', 'Evaluación')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=1200)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('completion_method', models.CharField(choices=[('view', 'Ver la actividad'), ('manual', 'Marcación explícita'), ('attendance', 'Cumplir asistencia'), ('submission', 'Enviar intento'), ('grade', 'Recibir calificación'), ('pass', 'Aprobar')], max_length=24)),
                ('minimum_attendance_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_grade_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_activities_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_activities_created', to=settings.AUTH_USER_MODEL)),
                ('lesson_unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='courses.courseunit')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='courses.coursemodule')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_activities_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CourseActivityAvailabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('activity_completed', 'Actividad completada'), ('activity_passed', 'Actividad aprobada'), ('minimum_grade', 'Calificación mínima'), ('objective_mastered', 'Objetivo dominado'), ('available_from', 'Disponible desde'), ('available_until', 'Disponible hasta')], max_length=32)),
                ('threshold_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_rules', to='courses.courseactivity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_activity_availability_rules_created', to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_availability_rules', to='catalog.learningobjective')),
                ('prerequisite_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_availability_rules', to='courses.courseactivity')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseActivityLearningObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_alignments', to='courses.courseactivity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_activity_objective_alignments_created', to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_activity_alignments', to='catalog.learningobjective')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CourseCompletionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_required_activities', models.BooleanField(default=True)),
                ('minimum_grade_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_attendance_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_completion_policies_confirmed', to=settings.AUTH_USER_MODEL)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_policy', to='courses.courserevision')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_completion_policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGradeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField()),
                ('weight_basis_points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_grade_categories_created', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_categories', to='courses.courserevision')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseGradedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_basis_points', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grade_item', to='courses.courseactivity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graded_activities', to='courses.coursegradecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_graded_activities_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_lesson_activities, reverse_lesson_activities),
        migrations.AddIndex(
            model_name='courseactivity',
            index=models.Index(fields=['module', 'status', 'position'], name='activity_module_state_pos_ix'),
        ),
        migrations.AddIndex(
            model_name='courseactivity',
            index=models.Index(fields=['activity_type', 'status'], name='activity_type_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='courseactivity',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('module', 'position'), name='courses_activity_module_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseactivity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('position__gt', 0), ('position__isnull', False), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('position__isnull', True), ('status', 'archived')), _connector='OR'), name='courses_activity_state_position'),
        ),
        migrations.AddConstraint(
            model_name='courseactivity',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_minutes__isnull', True), ('estimated_duration_minutes__gt', 0), _connector='OR'), name='courses_activity_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseactivity',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_attendance_basis_points__isnull', True), models.Q(('minimum_attendance_basis_points__gte', 1), ('minimum_attendance_basis_points__lte', 10000)), _connector='OR'), name='courses_activity_attendance_range'),
        ),
        migrations.AddConstraint(
            model_name='courseactivity',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_grade_basis_points__isnull', True), ('minimum_grade_basis_points__lte', 10000), _connector='OR'), name='courses_activity_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='courseactivityavailabilityrule',
            constraint=models.UniqueConstraint(fields=('activity', 'position'), name='courses_activity_rule_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseactivityavailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_activity_rule_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseactivityavailabilityrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_basis_points__isnull', True), ('threshold_basis_points__lte', 10000), _connector='OR'), name='courses_activity_rule_threshold_range'),
        ),
        migrations.AddConstraint(
            model_name='courseactivitylearningobjective',
            constraint=models.UniqueConstraint(fields=('activity', 'learning_objective'), name='courses_activity_objective_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseactivitylearningobjective',
            constraint=models.UniqueConstraint(fields=('activity', 'position'), name='courses_activity_objective_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='courseactivitylearningobjective',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_activity_objective_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='courses_completion_policy_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_grade_basis_points__isnull', True), ('minimum_grade_basis_points__lte', 10000), _connector='OR'), name='courses_completion_policy_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_attendance_basis_points__isnull', True), ('minimum_attendance_basis_points__lte', 10000), _connector='OR'), name='courses_completion_policy_attendance_range'),
        ),
        migrations.AddConstraint(
            model_name='coursecompletionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False)), _connector='OR'), name='courses_completion_policy_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='coursegradecategory',
            constraint=models.UniqueConstraint(fields=('revision', 'code'), name='courses_grade_category_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursegradecategory',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='courses_grade_category_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursegradecategory',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='courses_grade_category_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursegradecategory',
            constraint=models.CheckConstraint(condition=models.Q(('weight_basis_points__gte', 1), ('weight_basis_points__lte', 10000)), name='courses_grade_category_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='coursegradedactivity',
            constraint=models.CheckConstraint(condition=models.Q(('weight_basis_points__gte', 1), ('weight_basis_points__lte', 10000)), name='courses_graded_activity_weight_range'),
        ),
    ]
