# Generated by Django 6.0.7 on 2026-08-02 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseactivity_courseactivityavailabilityrule_and_more'),
        ('organizations', '0007_organization_activated_at_organization_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeachingException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('rationale', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_exceptions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_teaching_exceptions_created', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_teaching_exceptions_ended', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_teaching_exceptions', to='organizations.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('course', 'membership'), name='courses_course_teacher_active_unique'), models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='courses_course_teacher_date_window'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('ended_by__isnull', True)), models.Q(('ended_at__isnull', False), ('ended_by__isnull', False)), _connector='OR'), name='courses_course_teacher_end_state')],
            },
        ),
    ]
