from django.urls import path

from . import views

urlpatterns = [
    path(
        "organizations/<slug:slug>/catalog/teaching-responsibilities/",
        views.SubjectTeachingResponsibilityListCreateView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/teaching-responsibilities/<uuid:responsibility_id>/close/",
        views.CloseSubjectTeachingResponsibilityView.as_view(),
    ),
    path("organizations/<slug:slug>/catalog/areas/", views.AreaListView.as_view()),
    path(
        "organizations/<slug:slug>/catalog/areas/<uuid:area_id>/",
        views.AreaDetailView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/areas/<uuid:area_id>/archive/",
        views.ArchiveAreaView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/areas/<uuid:area_id>/restore/",
        views.RestoreAreaView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/disciplines/",
        views.DisciplineListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/disciplines/<uuid:discipline_id>/",
        views.DisciplineDetailView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/disciplines/<uuid:discipline_id>/archive/",
        views.ArchiveDisciplineView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/disciplines/<uuid:discipline_id>/restore/",
        views.RestoreDisciplineView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/subjects/", views.SubjectListView.as_view()
    ),
    path(
        "organizations/<slug:slug>/catalog/subjects/<uuid:subject_id>/",
        views.SubjectDetailView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/subjects/<uuid:subject_id>/archive/",
        views.ArchiveSubjectView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/subjects/<uuid:subject_id>/restore/",
        views.RestoreSubjectView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/subjects/<uuid:subject_id>/topics/",
        views.TopicListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/subjects/<uuid:subject_id>/prerequisites/",
        views.SubjectPrerequisiteView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/subject-prerequisites/",
        views.SubjectPrerequisiteListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/topics/<uuid:topic_id>/concepts/",
        views.TopicConceptAssociationView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/topic-concepts/",
        views.TopicConceptAssociationListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/topics/<uuid:topic_id>/",
        views.TopicDetailView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/topics/<uuid:topic_id>/move/",
        views.TopicMoveView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/topics/<uuid:topic_id>/archive/",
        views.ArchiveTopicView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/topics/<uuid:topic_id>/restore/",
        views.RestoreTopicView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/concepts/", views.ConceptListView.as_view()
    ),
    path(
        "organizations/<slug:slug>/catalog/concepts/<uuid:concept_id>/",
        views.ConceptDetailView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/concepts/<uuid:concept_id>/prerequisites/",
        views.ConceptPrerequisiteView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/concept-prerequisites/",
        views.ConceptPrerequisiteListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/concepts/<uuid:concept_id>/archive/",
        views.ArchiveConceptView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/concepts/<uuid:concept_id>/restore/",
        views.RestoreConceptView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/learning-objectives/",
        views.ObjectiveListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/learning-objectives/<uuid:objective_id>/concepts/",
        views.ObjectiveConceptAssociationView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/objective-concepts/",
        views.ObjectiveConceptAssociationListView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/learning-objectives/<uuid:objective_id>/",
        views.ObjectiveDetailView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/learning-objectives/<uuid:objective_id>/archive/",
        views.ArchiveObjectiveView.as_view(),
    ),
    path(
        "organizations/<slug:slug>/catalog/learning-objectives/<uuid:objective_id>/restore/",
        views.RestoreObjectiveView.as_view(),
    ),
]
