MAX_MATHJSON_NODES = 200
MAX_MATHJSON_DEPTH = 24
MAX_MATH_SYMBOLS = 10
MAX_LATEX_LENGTH = 4096
MAX_NUMBER_DIGITS = 100
MAX_INTEGER_EXPONENT_ABS = 20
MAX_VARIADIC_ARGUMENTS = 50
MAX_SYMBOLIC_OPERATIONS = 500
MAX_COUNTEREXAMPLE_EVALUATIONS = 32

COUNTEREXAMPLE_POINTS = (
    -5,
    -3,
    -2,
    -1,
    "-1/2",
    "1/2",
    1,
    2,
    3,
    5,
)
