# Generated by Django 6.0.7 on 2026-07-31 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=160)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('correlation_id', models.UUIDField()),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_events', to='organizations.organization')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EventConsumerDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('dead', 'Terminal')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='events.domainevent')),
            ],
        ),
        migrations.CreateModel(
            name='EventReplayRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(max_length=120)),
                ('event_type', models.CharField(blank=True, max_length=160)),
                ('from_event_id', models.UUIDField(blank=True, null=True)),
                ('to_event_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=16)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('processed_events', models.PositiveIntegerField(default=0)),
                ('failed_events', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_replay_requests_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_replay_requests', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['organization', '-occurred_at'], name='events_org_occurred_ix'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='events_type_occurred_ix'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='events_aggregate_ix'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['correlation_id'], name='events_correlation_ix'),
        ),
        migrations.AddConstraint(
            model_name='domainevent',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gt', 0)), name='events_schema_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='domainevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__regex', '^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*){2}\\.v[1-9][0-9]*$')), name='events_type_versioned_format'),
        ),
        migrations.AddIndex(
            model_name='eventconsumerdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='events_delivery_due_ix'),
        ),
        migrations.AddIndex(
            model_name='eventconsumerdelivery',
            index=models.Index(fields=['consumer_name', 'status'], name='events_consumer_state_ix'),
        ),
        migrations.AddIndex(
            model_name='eventconsumerdelivery',
            index=models.Index(fields=['lease_expires_at'], name='events_delivery_lease_ix'),
        ),
        migrations.AddConstraint(
            model_name='eventconsumerdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'consumer_name'), name='events_delivery_consumer_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventreplayrequest',
            constraint=models.CheckConstraint(condition=models.Q(('total_events__lte', 100000)), name='events_replay_size_limit'),
        ),
        migrations.AddConstraint(
            model_name='eventreplayrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='events_replay_reason_required'),
        ),
    ]
