# Generated by Django 6.0.7 on 2026-07-31 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION events_reject_domain_event_mutation()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              RAISE EXCEPTION 'DomainEvent is append-only' USING ERRCODE = '55000';
            END;
            $$;
            CREATE TRIGGER events_domain_event_append_only
            BEFORE UPDATE OR DELETE ON events_domainevent
            FOR EACH ROW EXECUTE FUNCTION events_reject_domain_event_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS events_domain_event_append_only ON events_domainevent;
            DROP FUNCTION IF EXISTS events_reject_domain_event_mutation();
            """,
        )
    ]
