# Generated by Django 6.0.7 on 2026-07-31 05:23

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('dataset', 'Dataset'), ('caption', 'Captions')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_upload', 'Pendiente de carga'), ('uploaded', 'Cargado'), ('scanning', 'Escaneando'), ('processing', 'Procesando'), ('ready', 'Listo'), ('rejected', 'Rechazado'), ('failed', 'Fallido')], default='pending_upload', max_length=24)),
                ('original_filename', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(max_length=128)),
                ('detected_mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('extension', models.CharField(blank=True, default='', max_length=16)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('storage_bucket', models.CharField(blank=True, default='', max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', max_length=1024)),
                ('storage_etag', models.CharField(blank=True, default='', max_length=255)),
                ('storage_checksum_algorithm', models.CharField(blank=True, default='', max_length=32)),
                ('storage_checksum_value', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_milliseconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('column_count', models.PositiveIntegerField(blank=True, null=True)),
                ('technical_metadata', models.JSONField(blank=True, default=dict)),
                ('pipeline_name', models.CharField(blank=True, default='', max_length=64)),
                ('pipeline_version', models.CharField(blank=True, default='', max_length=32)),
                ('expected_asset_lock_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('malware_signature', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('image_thumbnail', 'Miniatura'), ('image_medium', 'Imagen mediana'), ('image_large', 'Imagen grande'), ('image_web_fallback', 'Fallback web'), ('audio_playback', 'Audio reproducible'), ('video_playback', 'Video reproducible'), ('video_poster', 'Poster de video'), ('caption_normalized', 'Captions normalizados')], max_length=32)),
                ('pipeline_name', models.CharField(max_length=64)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('mime_type', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=16)),
                ('storage_bucket', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_milliseconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('technical_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='assets.assetversion')),
            ],
        ),
        migrations.CreateModel(
            name='AssetUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_method', models.CharField(choices=[('single', 'Simple'), ('multipart', 'Multipart')], max_length=16)),
                ('status', models.CharField(choices=[('initiated', 'Iniciada'), ('uploading', 'Cargando'), ('uploaded', 'Cargada'), ('completed', 'Completada'), ('aborted', 'Abortada'), ('expired', 'Expirada'), ('failed', 'Fallida')], default='initiated', max_length=16)),
                ('quarantine_bucket', models.CharField(max_length=255)),
                ('quarantine_key', models.CharField(max_length=1024)),
                ('declared_filename', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(max_length=128)),
                ('expected_size_bytes', models.PositiveBigIntegerField()),
                ('expected_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('multipart_upload_id', models.TextField(blank=True, default='')),
                ('part_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('aborted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_upload_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_upload_sessions', to='organizations.organization')),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='assets.assetversion')),
            ],
        ),
        migrations.CreateModel(
            name='AssetProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('initial_processing', 'Procesamiento inicial'), ('reprocess_variants', 'Reprocesar variantes')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En ejecución'), ('completed', 'Completado'), ('completed_with_errors', 'Completado con errores'), ('failed', 'Fallido')], default='queued', max_length=32)),
                ('stage', models.CharField(choices=[('queued', 'En cola'), ('downloading', 'Descargando'), ('scanning', 'Escaneando'), ('validating', 'Validando'), ('extracting_metadata', 'Extrayendo metadatos'), ('transcoding', 'Transcodificando'), ('uploading_variants', 'Subiendo variantes'), ('promoting_original', 'Promoviendo original'), ('cleaning_quarantine', 'Limpiando cuarentena'), ('completed', 'Completado')], default='queued', max_length=32)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('pipeline_name', models.CharField(max_length=64)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='assets.assetversion')),
            ],
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('asset_created', 'Asset creado'), ('upload_initialized', 'Carga iniciada'), ('upload_completed', 'Carga completada'), ('malware_scan_passed', 'Antivirus aprobado'), ('malware_detected', 'Malware detectado'), ('validation_passed', 'Validación aprobada'), ('validation_failed', 'Validación fallida'), ('processing_started', 'Procesamiento iniciado'), ('processing_completed', 'Procesamiento completado'), ('processing_failed', 'Procesamiento fallido'), ('version_promoted', 'Versión promovida'), ('asset_archived', 'Asset archivado'), ('asset_restored', 'Asset restaurado'), ('reprocess_requested', 'Reprocesamiento solicitado')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_events', to='organizations.organization')),
                ('processing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assets.assetprocessingjob')),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assets.assetuploadsession')),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assets.assetversion')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_asset', to='assets.assetversion'),
        ),
        migrations.CreateModel(
            name='AssetUploadPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.PositiveSmallIntegerField()),
                ('etag', models.CharField(max_length=255)),
                ('checksum_algorithm', models.CharField(blank=True, default='', max_length=32)),
                ('checksum_value', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='assets.assetuploadsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('upload_session', 'part_number'), name='assets_upload_part_number_unique'), models.CheckConstraint(condition=models.Q(('part_number__gte', 1), ('part_number__lte', 10000)), name='assets_upload_part_number_range'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='assets_upload_part_size_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['asset', 'status'], name='asset_version_asset_state_ix'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['status', 'created_at'], name='asset_version_state_created_ix'),
        ),
        migrations.AddIndex(
            model_name='assetversion',
            index=models.Index(fields=['sha256'], name='asset_version_sha_ix'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'number'), name='assets_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assets_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.CheckConstraint(condition=models.Q(('expected_asset_lock_version__gt', 0)), name='assets_version_expected_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.CheckConstraint(condition=models.Q(('sha256', ''), ('sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='assets_version_sha256_format'),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__isnull', True), ('size_bytes__gt', 0), _connector='OR'), name='assets_version_size_positive'),
        ),
        migrations.AddIndex(
            model_name='assetvariant',
            index=models.Index(fields=['asset_version', 'role'], name='asset_variant_version_role_ix'),
        ),
        migrations.AddIndex(
            model_name='assetvariant',
            index=models.Index(fields=['sha256'], name='asset_variant_sha_ix'),
        ),
        migrations.AddConstraint(
            model_name='assetvariant',
            constraint=models.UniqueConstraint(fields=('asset_version', 'pipeline_name', 'pipeline_version', 'role'), name='assets_variant_pipeline_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='assetvariant',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='assets_variant_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='assets_variant_sha256_format'),
        ),
        migrations.AddIndex(
            model_name='assetuploadsession',
            index=models.Index(fields=['organization', 'status'], name='asset_upload_org_state_ix'),
        ),
        migrations.AddIndex(
            model_name='assetuploadsession',
            index=models.Index(fields=['created_by', 'status'], name='asset_upload_user_state_ix'),
        ),
        migrations.AddIndex(
            model_name='assetuploadsession',
            index=models.Index(fields=['expires_at'], name='asset_upload_expiry_ix'),
        ),
        migrations.AddConstraint(
            model_name='assetuploadsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['initiated', 'uploading', 'uploaded'])), fields=('asset_version',), name='assets_one_active_upload_per_version'),
        ),
        migrations.AddConstraint(
            model_name='assetuploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_size_bytes__gt', 0)), name='assets_upload_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetuploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_sha256', ''), ('expected_sha256__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='assets_upload_sha256_format'),
        ),
        migrations.AddIndex(
            model_name='assetprocessingjob',
            index=models.Index(fields=['asset_version', 'status'], name='asset_job_version_state_ix'),
        ),
        migrations.AddIndex(
            model_name='assetprocessingjob',
            index=models.Index(fields=['status', 'created_at'], name='asset_job_state_created_ix'),
        ),
        migrations.AddIndex(
            model_name='assetprocessingjob',
            index=models.Index(fields=['task_id'], name='asset_job_task_ix'),
        ),
        migrations.AddConstraint(
            model_name='assetprocessingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('asset_version', 'pipeline_name', 'pipeline_version'), name='assets_one_active_job_per_pipeline'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['organization', 'created_at'], name='asset_event_org_created_ix'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['asset', 'created_at'], name='asset_event_asset_created_ix'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'kind', 'status'], name='asset_org_kind_state_ix'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['updated_at'], name='asset_updated_ix'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim(models.F('name'))), models.Q(('name', ''), _negated=True)), name='assets_name_trimmed_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assets_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived')), _connector='OR'), name='assets_archive_state'),
        ),
    ]
