# Generated by Django 6.0.7 on 2026-07-31 19:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.contrib.postgres.operations
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='SearchGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('building', 'Construyendo'), ('active', 'Activa'), ('failed', 'Fallida'), ('superseded', 'Reemplazada')], max_length=16)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_generations_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_generations', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', '-number'),
            },
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('course_release', 'Release de curso'), ('course_unit', 'Unidad de curso'), ('catalog_subject', 'Asignatura'), ('catalog_topic', 'Tema'), ('catalog_concept', 'Concepto'), ('learning_objective', 'Objetivo'), ('asset_version', 'Versión de asset'), ('question_version', 'Versión de pregunta'), ('assessment_version', 'Versión de evaluación')], max_length=40)),
                ('source_id', models.UUIDField()),
                ('source_version_id', models.UUIDField(blank=True, null=True)),
                ('audience', models.CharField(choices=[('learning', 'Aprendizaje'), ('authoring', 'Autoría'), ('institutional', 'Institucional')], max_length=20)),
                ('language_code', models.CharField(default='es', max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('body_plain_text', models.TextField(blank=True)),
                ('normalized_title', models.CharField(max_length=300)),
                ('url_path', models.CharField(max_length=1000)),
                ('metadata', models.JSONField(default=dict)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('content_digest', models.CharField(max_length=64)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_documents', to='organizations.organization')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='discovery.searchgeneration')),
            ],
        ),
        migrations.CreateModel(
            name='SearchIndexJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('course_release', 'Release de curso'), ('course_unit', 'Unidad de curso'), ('catalog_subject', 'Asignatura'), ('catalog_topic', 'Tema'), ('catalog_concept', 'Concepto'), ('learning_objective', 'Objetivo'), ('asset_version', 'Versión de asset'), ('question_version', 'Versión de pregunta'), ('assessment_version', 'Versión de evaluación')], max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('source_version_id', models.UUIDField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('upsert', 'Actualizar'), ('deactivate', 'Desactivar'), ('rebuild', 'Reconstruir')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_index_jobs', to='events.domainevent')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='discovery.searchgeneration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_index_jobs', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='searchgeneration',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='discovery_generation_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='searchgeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization',), name='discovery_one_active_generation'),
        ),
        migrations.AddConstraint(
            model_name='searchgeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'building')), fields=('organization',), name='discovery_one_building_generation'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='discovery_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('normalized_title', name='gin_trgm_ops'), name='discovery_title_trgm_gin'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['generation', 'audience', 'source_type'], name='discovery_generation_aud_ix'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['organization', 'source_id'], name='discovery_org_source_ix'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['source_version_id'], name='discovery_source_version_ix'),
        ),
        migrations.AddConstraint(
            model_name='searchdocument',
            constraint=models.UniqueConstraint(fields=('generation', 'source_type', 'source_version_id', 'audience'), name='discovery_document_source_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='searchdocument',
            constraint=models.CheckConstraint(condition=models.Q(('language_code__in', ('es', 'en'))), name='discovery_language_supported'),
        ),
        migrations.AddIndex(
            model_name='searchindexjob',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='discovery_job_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='searchindexjob',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'operation'), name='discovery_event_operation_unique'),
        ),
    ]
