# Generated by Django 6.0.7 on 2026-07-31 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    # The extension must precede the trigram index created in 0001. This
    # generated empty migration remains as the explicit phase marker.
    operations: list[migrations.Migration] = []
