# Generated by Django 6.0.7 on 2026-07-31 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_enable_pg_trgm'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchdocument',
            name='discovery_document_source_unique',
        ),
        migrations.AlterField(
            model_name='searchindexjob',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='discovery.searchgeneration'),
        ),
        migrations.AddConstraint(
            model_name='searchdocument',
            constraint=models.UniqueConstraint(fields=('generation', 'source_type', 'source_id', 'source_version_id', 'audience'), name='discovery_document_source_unique', nulls_distinct=False),
        ),
    ]
