# Generated by Django 6.0.7 on 2026-08-01 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('public_signup_enabled', models.BooleanField(default=True)),
                ('signup_mode', models.CharField(choices=[('closed', 'Cerrado'), ('invite_only', 'Sólo invitación'), ('open', 'Abierto')], default='open', max_length=16)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('default_locale', models.CharField(default='es', max_length=16)),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_registration_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_platform_registration', 'Can manage platform registration')],
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='identity_registration_settings_singleton_one'), models.CheckConstraint(condition=models.Q(models.Q(('public_signup_enabled', True), ('signup_mode', 'open')), models.Q(('public_signup_enabled', False), ('signup_mode__in', ['closed', 'invite_only'])), _connector='OR'), name='identity_registration_settings_mode_consistent'), models.CheckConstraint(condition=models.Q(('require_email_verification', True)), name='identity_registration_settings_email_verification_required')],
            },
        ),
    ]
