# Generated by Django 6.0.7 on 2026-07-29 08:28

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_areas', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('definition', models.TextField(max_length=3000)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concepts', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptPrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('required', 'Obligatorio'), ('recommended', 'Recomendado')], max_length=16)),
                ('rationale', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_links', to='catalog.concept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_links', to='catalog.concept')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='catalog.academicarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('statement', models.TextField(max_length=1200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('cognitive_level', models.CharField(blank=True, choices=[('remember', 'Recordar'), ('understand', 'Comprender'), ('apply', 'Aplicar'), ('analyze', 'Analizar'), ('evaluate', 'Evaluar'), ('create', 'Crear')], max_length=16)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjectiveConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_links', to='catalog.concept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_links', to='catalog.learningobjective')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='catalog.discipline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_objectives', to='catalog.subject'),
        ),
        migrations.CreateModel(
            name='SubjectPrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('required', 'Obligatorio'), ('recommended', 'Recomendado')], max_length=16)),
                ('rationale', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_links', to='catalog.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_links', to='catalog.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_topics', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='catalog.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_links', to='catalog.concept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_links', to='catalog.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='academicarea',
            index=models.Index(fields=['organization', 'status'], name='catalog_area_org_status_ix'),
        ),
        migrations.AddConstraint(
            model_name='academicarea',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('slug'), name='catalog_area_org_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='academicarea',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim(models.F('name'))), models.Q(('name', ''), _negated=True)), name='catalog_area_name_trimmed'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['organization', 'status'], name='catalog_concept_org_status_ix'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('slug'), name='catalog_concept_org_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisite',
            constraint=models.UniqueConstraint(models.F('concept'), models.F('prerequisite'), name='catalog_concept_prerequisite_unique'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('concept', models.F('prerequisite')), _negated=True), name='catalog_concept_prerequisite_not_self'),
        ),
        migrations.AddIndex(
            model_name='discipline',
            index=models.Index(fields=['area', 'status'], name='cat_discipline_area_status_ix'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(models.F('area'), django.db.models.functions.text.Lower('slug'), name='catalog_discipline_area_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectiveconcept',
            constraint=models.UniqueConstraint(models.F('learning_objective'), models.F('concept'), name='catalog_objective_concept_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectiveconcept',
            constraint=models.UniqueConstraint(models.F('learning_objective'), models.F('position'), name='catalog_objective_concept_position_unique'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['discipline', 'status'], name='cat_subject_discipline_ix'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(models.F('discipline'), django.db.models.functions.text.Lower('slug'), name='catalog_subject_discipline_slug_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='learningobjective',
            index=models.Index(fields=['subject', 'status'], name='cat_objective_subject_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(models.F('subject'), django.db.models.functions.text.Lower('code'), name='catalog_objective_subject_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9_.-]+$')), name='catalog_objective_code_format'),
        ),
        migrations.AddConstraint(
            model_name='subjectprerequisite',
            constraint=models.UniqueConstraint(models.F('subject'), models.F('prerequisite'), name='catalog_subject_prerequisite_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('subject', models.F('prerequisite')), _negated=True), name='catalog_subject_prerequisite_not_self'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'status'], name='cat_topic_subject_status_ix'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(models.F('subject'), django.db.models.functions.text.Lower('slug'), name='catalog_topic_subject_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='topicconcept',
            constraint=models.UniqueConstraint(models.F('topic'), models.F('concept'), name='catalog_topic_concept_unique'),
        ),
        migrations.AddConstraint(
            model_name='topicconcept',
            constraint=models.UniqueConstraint(models.F('topic'), models.F('position'), name='catalog_topic_concept_position_unique'),
        ),
    ]
