# Generated by Django 6.0.7 on 2026-07-30 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitContentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_content_documents_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='content_document', to='courses.courseunit')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_content_documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(editable=False)),
                ('schema_version', models.PositiveIntegerField(editable=False)),
                ('content', models.JSONField(editable=False)),
                ('plain_text', models.TextField(editable=False)),
                ('character_count', models.PositiveIntegerField(editable=False)),
                ('word_count', models.PositiveIntegerField(editable=False)),
                ('node_count', models.PositiveIntegerField(editable=False)),
                ('digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_content_versions_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.unitcontentdocument')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddField(
            model_name='unitcontentdocument',
            name='current_version',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='content.unitcontentversion'),
        ),
        migrations.AddIndex(
            model_name='unitcontentversion',
            index=models.Index(fields=['document', 'created_at'], name='content_ver_doc_created_ix'),
        ),
        migrations.AddIndex(
            model_name='unitcontentversion',
            index=models.Index(fields=['digest'], name='content_version_digest_ix'),
        ),
        migrations.AddIndex(
            model_name='unitcontentversion',
            index=models.Index(fields=['created_by', 'created_at'], name='content_ver_actor_created_ix'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='content_version_document_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='content_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gt', 0)), name='content_version_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.CheckConstraint(condition=models.Q(('character_count__gte', 0)), name='content_version_chars_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.CheckConstraint(condition=models.Q(('word_count__gte', 0)), name='content_version_words_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.CheckConstraint(condition=models.Q(('node_count__gte', 0)), name='content_version_nodes_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='unitcontentversion',
            constraint=models.CheckConstraint(condition=models.Q(('digest__regex', '^[0-9a-f]{64}$')), name='content_version_digest_sha256'),
        ),
        migrations.AddIndex(
            model_name='unitcontentdocument',
            index=models.Index(fields=['updated_at'], name='content_document_updated_ix'),
        ),
    ]
