# Generated by Django 6.0.7 on 2026-07-31 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_enforce_asset_immutability'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAssetReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.UUIDField(editable=False)),
                ('reference_role', models.CharField(choices=[('primary', 'Primary'), ('captions', 'Captions')], editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_references', to='assets.assetversion')),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_references', to='content.unitcontentversion')),
            ],
            options={
                'indexes': [models.Index(fields=['content_version'], name='content_asset_ref_version_ix'), models.Index(fields=['asset_version'], name='content_asset_ref_asset_ix'), models.Index(fields=['node_id'], name='content_asset_ref_node_ix')],
                'constraints': [models.UniqueConstraint(fields=('content_version', 'node_id', 'reference_role'), name='content_asset_ref_node_role_unique')],
            },
        ),
    ]
