# Generated by Django 6.0.7 on 2026-07-31 05:36

from django.db import migrations

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION content_reject_asset_reference_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'ContentAssetReference is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER content_asset_reference_no_update
BEFORE UPDATE ON content_contentassetreference
FOR EACH ROW EXECUTE FUNCTION content_reject_asset_reference_mutation();

CREATE TRIGGER content_asset_reference_no_delete
BEFORE DELETE ON content_contentassetreference
FOR EACH ROW EXECUTE FUNCTION content_reject_asset_reference_mutation();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS content_asset_reference_no_update
ON content_contentassetreference;
DROP TRIGGER IF EXISTS content_asset_reference_no_delete
ON content_contentassetreference;
DROP FUNCTION IF EXISTS content_reject_asset_reference_mutation();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentassetreference'),
    ]

    operations = [migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER)]
