# Generated by Django 6.0.7 on 2026-08-04 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_enforce_asset_immutability'),
        ('content', '0003_enforce_content_asset_reference_immutability'),
        ('courses', '0005_mediacmsvideobinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLessonResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_resource_bindings', to='assets.assetversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_resources_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_resource', to='courses.courseunit')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_resources_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['asset_version'], name='content_lesson_res_asset_ix')],
            },
        ),
    ]
