# Generated by Django 6.0.7 on 2026-07-31 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('learning', 'Aprendizaje'), ('assessment', 'Evaluación'), ('authoring', 'Autoría'), ('asset', 'Recurso'), ('publication', 'Publicación'), ('system', 'Sistema')], max_length=20)),
                ('template_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('action_url', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='events.domainevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='organizations.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('dead', 'Terminal')], default='queued', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('recipient_email_hash', models.CharField(max_length=64)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('dead', 'Terminal')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='notifications.emaildelivery')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('learning', 'Aprendizaje'), ('assessment', 'Evaluación'), ('authoring', 'Autoría'), ('asset', 'Recurso'), ('publication', 'Publicación'), ('system', 'Sistema')], max_length=20)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_recipient_unread_ix'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notifications_recipient_cat_ix'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event'], name='notifications_event_ix'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('event', 'recipient', 'template_key'), name='notifications_event_recipient_template_unique'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('action_url', ''), ('action_url__startswith', '/'), _connector='OR'), name='notifications_action_url_relative'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notifications_email_due_ix'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['recipient'], name='notif_email_recipient_ix'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='notifications_preference_unique'),
        ),
    ]
