# Generated by Django 6.0.7 on 2026-07-31 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION notifications_reject_delivery_event_mutation()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              RAISE EXCEPTION 'NotificationDeliveryEvent is append-only' USING ERRCODE = '55000';
            END;
            $$;
            CREATE TRIGGER notifications_delivery_event_append_only
            BEFORE UPDATE OR DELETE ON notifications_notificationdeliveryevent
            FOR EACH ROW EXECUTE FUNCTION notifications_reject_delivery_event_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS notifications_delivery_event_append_only ON notifications_notificationdeliveryevent;
            DROP FUNCTION IF EXISTS notifications_reject_delivery_event_mutation();
            """,
        )
    ]
