# Generated by Django 6.0.7 on 2026-07-30 17:37

import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('learning', '0003_enforce_cohort_release_immutability'),
        ('organizations', '0001_initial'),
        ('publishing', '0002_enforce_release_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('points', models.DecimalField(decimal_places=3, max_digits=12)),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentItemObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_item_objectives_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_links', to='assessments.assessmentitem')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_item_links', to='catalog.learningobjective')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('instructions', models.TextField(blank=True, max_length=10000)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_basis_points', models.PositiveIntegerField(default=6000)),
                ('shuffle_sections', models.BooleanField(default=False)),
                ('shuffle_items', models.BooleanField(default=False)),
                ('feedback_mode', models.CharField(choices=[('none', 'Sin retroalimentación'), ('after_submission', 'Después del envío'), ('after_grading', 'Después de calificar')], default='after_grading', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobado')], default='draft', max_length=24)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('status_changed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessments.assessment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_revisions_status_changed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_revisions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentRevisionObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_revision_objectives_created', to=settings.AUTH_USER_MODEL)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_revision_links', to='catalog.learningobjective')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_links', to='assessments.assessmentrevision')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentRevisionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobado')], max_length=24)),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobado')], max_length=24)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_revision_transitions', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='assessments.assessmentrevision')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, max_length=5000)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sections_created', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='assessments.assessmentrevision')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sections_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessments.assessmentsection'),
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1, editable=False)),
                ('public_snapshot', models.JSONField(editable=False)),
                ('grading_snapshot', models.JSONField(editable=False)),
                ('snapshot_digest', models.CharField(editable=False, max_length=64)),
                ('title', models.CharField(editable=False, max_length=200)),
                ('description', models.TextField(blank=True, editable=False, max_length=5000)),
                ('section_count', models.PositiveIntegerField(editable=False)),
                ('item_count', models.PositiveIntegerField(editable=False)),
                ('maximum_score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('attempt_limit', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('pass_basis_points', models.PositiveIntegerField(editable=False)),
                ('feedback_mode', models.CharField(choices=[('none', 'Sin retroalimentación'), ('after_submission', 'Después del envío'), ('after_grading', 'Después de calificar')], editable=False, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessments.assessment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_versions_created', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='assessments.assessmentversion')),
                ('source_revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='version', to='assessments.assessmentrevision')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='assessmentrevision',
            name='based_on_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_revisions', to='assessments.assessmentversion'),
        ),
        migrations.CreateModel(
            name='AssessmentDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('withdrawn', 'Retirada')], default='draft', max_length=16)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_note', models.TextField(blank=True, max_length=2000)),
                ('course_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_deliveries', to='publishing.courserelease')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_deliveries', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_deliveries_updated', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_deliveries_withdrawn', to=settings.AUTH_USER_MODEL)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='assessments.assessmentversion')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'En curso'), ('pending_manual', 'Pendiente de calificación manual'), ('graded', 'Calificado')], default='in_progress', max_length=24)),
                ('seed', models.PositiveBigIntegerField(editable=False)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('auto_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('manual_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('total_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('maximum_score', models.DecimalField(decimal_places=3, max_digits=12)),
                ('basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessmentversion')),
            ],
            options={
                'ordering': ('attempt_number',),
            },
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Iniciado'), ('response_saved', 'Respuesta guardada'), ('submitted', 'Enviado'), ('auto_graded', 'Calificado automáticamente'), ('manual_graded', 'Calificado manualmente'), ('completed', 'Completado')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_attempt_events', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assessments.attempt')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('revoked', 'Revocada')], default='active', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_assignments', to='learning.learningcohort')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assessments.assessmentdelivery')),
                ('release_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_assignments', to='learning.enrollmentreleaseassignment')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_assignments_revoked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='delivery_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.deliveryassignment'),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_banks_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_banks_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions_created', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBankVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(editable=False)),
                ('snapshot_digest', models.CharField(editable=False, max_length=64)),
                ('question_count', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessments.questionbank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_versions_created', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='assessments.questionbankversion')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('true_false', 'Verdadero o falso'), ('numeric', 'Numérica'), ('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('ordering', 'Ordenamiento'), ('matching', 'Emparejamiento')], max_length=24)),
                ('definition', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobado')], default='draft', max_length=24)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('status_changed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessments.question')),
                ('status_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_revisions_status_changed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_revisions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionRevisionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobado')], max_length=24)),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('changes_requested', 'Cambios solicitados'), ('approved', 'Aprobado')], max_length=24)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_revision_transitions', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='assessments.questionrevision')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('schema_version', models.PositiveIntegerField(default=1, editable=False)),
                ('type', models.CharField(choices=[('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('true_false', 'Verdadero o falso'), ('numeric', 'Numérica'), ('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('ordering', 'Ordenamiento'), ('matching', 'Emparejamiento')], editable=False, max_length=24)),
                ('public', models.JSONField(editable=False)),
                ('grading', models.JSONField(editable=False)),
                ('feedback', models.JSONField(editable=False)),
                ('definition_digest', models.CharField(editable=False, max_length=64)),
                ('public_digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_versions_created', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessments.question')),
                ('source_revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='version', to='assessments.questionrevision')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='questionrevision',
            name='based_on_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_revisions', to='assessments.questionversion'),
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_item_id', models.UUIDField(editable=False)),
                ('section_position', models.PositiveIntegerField(editable=False)),
                ('item_position', models.PositiveIntegerField(editable=False)),
                ('display_position', models.PositiveIntegerField(editable=False)),
                ('points', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('required', models.BooleanField(editable=False)),
                ('public_snapshot', models.JSONField(editable=False)),
                ('grading_snapshot', models.JSONField(editable=False)),
                ('feedback_snapshot', models.JSONField(editable=False)),
                ('snapshot_digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessments.attempt')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='assessments.questionversion')),
            ],
            options={
                'ordering': ('display_position',),
            },
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items', to='assessments.questionversion'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('status', models.CharField(choices=[('unanswered', 'Sin respuesta'), ('saved', 'Guardada'), ('auto_graded', 'Calificada automáticamente'), ('pending_manual', 'Pendiente de calificación manual'), ('manually_graded', 'Calificada manualmente')], default='saved', max_length=24)),
                ('score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('grading_version', models.PositiveIntegerField(default=1)),
                ('saved_at', models.DateTimeField()),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='assessments.attemptitem')),
            ],
        ),
        migrations.CreateModel(
            name='ManualGradeDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=12)),
                ('feedback', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_grade_decisions', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_decisions', to='assessments.response')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['organization', 'status'], name='assess_a_org_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('organization'), name='assess_assessment_org_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='assess_assessment_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived')), _connector='OR'), name='assess_assessment_archive_state'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitemobjective',
            constraint=models.UniqueConstraint(fields=('item', 'objective'), name='assess_item_objective_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitemobjective',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('item', 'position'), name='assess_item_objective_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitemobjective',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_item_objective_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevisionobjective',
            constraint=models.UniqueConstraint(fields=('revision', 'objective'), name='assess_arev_objective_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevisionobjective',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('revision', 'position'), name='assess_arev_objective_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevisionobjective',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_arev_objective_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevisiontransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='assess_atransition_changes_state'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('revision', 'position'), name='assess_section_revision_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_section_position_positive'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['assessment', 'created_at'], name='assess_aver_a_created_ix'),
        ),
        migrations.AddIndex(
            model_name='assessmentversion',
            index=models.Index(fields=['snapshot_digest'], name='assess_aver_digest_ix'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.UniqueConstraint(fields=('assessment', 'number'), name='assess_aversion_assessment_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_aversion_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gt', 0)), name='assess_aversion_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_digest__regex', '^[0-9a-f]{64}$')), name='assess_aversion_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('item_count__gt', 0)), name='assess_aversion_items_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_score__gt', Decimal('0'))), name='assess_aversion_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('pass_basis_points__gte', 0), ('pass_basis_points__lte', 10000)), name='assess_aversion_pass_bps_range'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('previous_version__isnull', True), models.Q(('previous_version', models.F('id')), _negated=True), _connector='OR'), name='assess_aversion_not_self'),
        ),
        migrations.AddIndex(
            model_name='assessmentrevision',
            index=models.Index(fields=['assessment', 'status'], name='assess_arev_a_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.UniqueConstraint(fields=('assessment', 'number'), name='assess_arev_assessment_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved'), _negated=True), fields=('assessment',), name='assess_arev_one_open'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_arev_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_arev_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('pass_basis_points__gte', 0), ('pass_basis_points__lte', 10000)), name='assess_arev_pass_bps_range'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_minutes__isnull', True), ('time_limit_minutes__gt', 0), _connector='OR'), name='assess_arev_time_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_limit__isnull', True), ('attempt_limit__gt', 0), _connector='OR'), name='assess_arev_attempt_positive'),
        ),
        migrations.AddIndex(
            model_name='assessmentdelivery',
            index=models.Index(fields=['organization', 'status'], name='assess_del_org_state_ix'),
        ),
        migrations.AddIndex(
            model_name='assessmentdelivery',
            index=models.Index(fields=['course_release', 'status'], name='assess_del_rel_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_delivery_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__isnull', True), ('closes_at__isnull', True), ('opens_at__lt', models.F('closes_at')), _connector='OR'), name='assess_delivery_window'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('unit_id__isnull', True), ('course_release__isnull', False), _connector='OR'), name='assess_delivery_unit_requires_release'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'withdrawn'), _negated=True), ('withdrawal_note', ''), ('withdrawn_at__isnull', True), ('withdrawn_by__isnull', True)), models.Q(('status', 'withdrawn'), ('withdrawn_at__isnull', False), ('withdrawn_by__isnull', False), models.Q(('withdrawal_note', ''), _negated=True)), _connector='OR'), name='assess_delivery_withdraw_state'),
        ),
        migrations.AddIndex(
            model_name='attemptevent',
            index=models.Index(fields=['attempt', 'created_at'], name='assess_evt_att_created_ix'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['release_assignment', 'status'], name='assess_assign_release_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('delivery', 'release_assignment'), name='assess_assignment_one_active'),
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='assess_assignment_revoke_state'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['delivery_assignment', 'status'], name='assess_att_assign_state_ix'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['assessment_version', 'status'], name='assess_att_ver_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('delivery_assignment', 'attempt_number'), name='assess_attempt_assignment_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='assess_attempt_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_attempt_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_score__gt', Decimal('0'))), name='assess_attempt_maximum_positive'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('auto_score__gte', Decimal('0')), ('manual_score__gte', Decimal('0')), ('total_score__gte', Decimal('0')), ('total_score__lte', models.F('maximum_score'))), name='assess_attempt_scores_range'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('basis_points__isnull', True), models.Q(('basis_points__gte', 0), ('basis_points__lte', 10000)), _connector='OR'), name='assess_attempt_bps_range'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['organization', 'status'], name='assess_bank_org_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('organization'), name='assess_bank_org_slug_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='assess_bank_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim(models.F('name'))), models.Q(('name', ''), _negated=True)), name='assess_bank_name_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_bank_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived')), _connector='OR'), name='assess_bank_archive_state'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank', 'status'], name='assess_q_bank_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(models.F('bank'), django.db.models.functions.text.Lower('code'), name='assess_question_bank_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Trim(models.F('code'))), models.Q(('code', ''), _negated=True)), name='assess_question_code_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived')), _connector='OR'), name='assess_question_archive_state'),
        ),
        migrations.AddConstraint(
            model_name='questionbankversion',
            constraint=models.UniqueConstraint(fields=('bank', 'number'), name='assess_bankversion_bank_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionbankversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_bankversion_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionbankversion',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_digest__regex', '^[0-9a-f]{64}$')), name='assess_bankversion_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='questionbankversion',
            constraint=models.CheckConstraint(condition=models.Q(('previous_version__isnull', True), models.Q(('previous_version', models.F('id')), _negated=True), _connector='OR'), name='assess_bankversion_not_self'),
        ),
        migrations.AddConstraint(
            model_name='questionrevisiontransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='assess_qtransition_changes_state'),
        ),
        migrations.AddIndex(
            model_name='questionversion',
            index=models.Index(fields=['question', 'created_at'], name='assess_qver_q_created_ix'),
        ),
        migrations.AddIndex(
            model_name='questionversion',
            index=models.Index(fields=['definition_digest'], name='assess_qver_def_digest_ix'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'number'), name='assess_qversion_question_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_qversion_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gt', 0)), name='assess_qversion_schema_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('definition_digest__regex', '^[0-9a-f]{64}$')), name='assess_qversion_definition_sha256'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('public_digest__regex', '^[0-9a-f]{64}$')), name='assess_qversion_public_sha256'),
        ),
        migrations.AddIndex(
            model_name='questionrevision',
            index=models.Index(fields=['question', 'status'], name='assess_qrev_q_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(fields=('question', 'number'), name='assess_qrev_question_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved'), _negated=True), fields=('question',), name='assess_qrev_one_open'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_qrev_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_qrev_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'assessment_item_id'), name='assess_attemptitem_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'display_position'), name='assess_attemptitem_display_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', Decimal('0'))), name='assess_attemptitem_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_digest__regex', '^[0-9a-f]{64}$')), name='assess_attemptitem_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('section', 'position'), name='assess_item_section_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('section', 'question_version'), name='assess_item_section_qversion_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', Decimal('0'))), name='assess_item_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', Decimal('0'))), name='assess_response_score_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.CheckConstraint(condition=models.Q(('grading_version__gt', 0)), name='assess_response_grading_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='manualgradedecision',
            constraint=models.UniqueConstraint(fields=('response', 'sequence'), name='assess_manual_response_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='manualgradedecision',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='assess_manual_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='manualgradedecision',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', Decimal('0'))), name='assess_manual_score_nonnegative'),
        ),
    ]
