# Generated by Django 6.0.7 on 2026-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_enforce_assessment_immutability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('delivery_assignment',), name='assess_attempt_one_in_progress'),
        ),
    ]
