# Generated by Django 6.0.7 on 2026-07-30 19:45

from django.db import migrations, models


def migrate_feedback_modes(apps, schema_editor):
    del schema_editor
    mappings = {
        "after_submission": "score_only",
        "after_grading": "full_after_grading",
    }
    for model_name in ("AssessmentRevision", "AssessmentVersion"):
        model = apps.get_model("assessments", model_name)
        for previous, current in mappings.items():
            model.objects.filter(feedback_mode=previous).update(feedback_mode=current)


def reverse_feedback_modes(apps, schema_editor):
    del schema_editor
    mappings = {
        "score_only": "after_submission",
        "full_after_grading": "after_grading",
    }
    for model_name in ("AssessmentRevision", "AssessmentVersion"):
        model = apps.get_model("assessments", model_name)
        for current, previous in mappings.items():
            model.objects.filter(feedback_mode=current).update(feedback_mode=previous)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_attempt_assess_attempt_one_in_progress'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE assessments_assessmentversion "
            "DISABLE TRIGGER assessments_aversion_reject_update;",
            reverse_sql=(
                "ALTER TABLE assessments_assessmentversion "
                "ENABLE TRIGGER assessments_aversion_reject_update;"
            ),
        ),
        migrations.RunPython(migrate_feedback_modes, reverse_feedback_modes),
        migrations.RunSQL(
            "ALTER TABLE assessments_assessmentversion "
            "ENABLE TRIGGER assessments_aversion_reject_update;",
            reverse_sql=(
                "ALTER TABLE assessments_assessmentversion "
                "DISABLE TRIGGER assessments_aversion_reject_update;"
            ),
        ),
        migrations.AlterField(
            model_name='assessmentrevision',
            name='feedback_mode',
            field=models.CharField(choices=[('none', 'Sin retroalimentación'), ('score_only', 'Sólo puntaje después de calificar'), ('full_after_grading', 'Retroalimentación completa después de calificar')], default='full_after_grading', max_length=24),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='feedback_mode',
            field=models.CharField(choices=[('none', 'Sin retroalimentación'), ('score_only', 'Sólo puntaje después de calificar'), ('full_after_grading', 'Retroalimentación completa después de calificar')], editable=False, max_length=24),
        ),
    ]
