# Generated by Django 6.0.7 on 2026-07-30 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentrevision_feedback_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentrevision',
            name='assess_arev_time_positive',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentrevision',
            name='assess_arev_attempt_positive',
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_minutes__isnull', True), models.Q(('time_limit_minutes__gt', 0), ('time_limit_minutes__lte', 10080)), _connector='OR'), name='assess_arev_time_range'),
        ),
        migrations.AddConstraint(
            model_name='assessmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_limit__isnull', True), models.Q(('attempt_limit__gt', 0), ('attempt_limit__lte', 20)), _connector='OR'), name='assess_arev_attempt_range'),
        ),
    ]
