# Generated by Django 6.0.7 on 2026-07-30 23:04

import django.db.models.constraints
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_remove_assessmentrevision_assess_arev_time_positive_and_more'),
        ('learning', '0003_enforce_cohort_release_immutability'),
        ('organizations', '0001_initial'),
        ('publishing', '0002_enforce_release_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPoolCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttemptGradeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('initial', 'Inicial'), ('manual_grade', 'Calificación manual'), ('regrade', 'Recalificación')], max_length=16)),
                ('scoring_engine_version', models.PositiveIntegerField(editable=False)),
                ('automatic_score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('manual_score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('final_score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('maximum_score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('percent_basis_points', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('passed', models.BooleanField(blank=True, editable=False, null=True)),
                ('grading_status', models.CharField(choices=[('pending', 'Pendiente'), ('pending_manual', 'Pendiente de revisión manual'), ('graded', 'Calificado'), ('failed', 'Falló')], editable=False, max_length=24)),
                ('digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='AttemptGradingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En ejecución'), ('completed', 'Completado'), ('completed_with_errors', 'Completado con errores'), ('failed', 'Falló')], default='queued', max_length=24)),
                ('task_id', models.UUIDField(editable=False, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptItemGradeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_basis_points', models.PositiveIntegerField(editable=False)),
                ('score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('maximum_score', models.DecimalField(decimal_places=3, editable=False, max_digits=12)),
                ('grading_status', models.CharField(choices=[('pending', 'Pendiente'), ('pending_manual', 'Pendiente de revisión manual'), ('graded', 'Calificado'), ('failed', 'Falló')], editable=False, max_length=24)),
                ('is_correct', models.BooleanField(blank=True, editable=False, null=True)),
                ('feedback_key', models.CharField(blank=True, editable=False, max_length=64)),
                ('manual_review_reason', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('attempt_item__display_position',),
            },
        ),
        migrations.CreateModel(
            name='CourseGradebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo')], default='draft', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradebookColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('weight_basis_points', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('attempt_aggregation', models.CharField(choices=[('highest', 'Mejor intento'), ('latest', 'Último intento')], default='highest', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GradebookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('missing', 'Sin entrega'), ('pending', 'Pendiente'), ('graded', 'Calificada')], default='missing', max_length=16)),
                ('score', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('maximum_score', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('percent_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradebookSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=16)),
                ('completed_columns', models.PositiveIntegerField(default=0)),
                ('total_columns', models.PositiveIntegerField(default=0)),
                ('weighted_percent_basis_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_item_id', models.UUIDField(editable=False)),
                ('question_type', models.CharField(choices=[('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('true_false', 'Verdadero o falso'), ('numeric', 'Numérica'), ('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('ordering', 'Ordenamiento'), ('matching', 'Emparejamiento'), ('mathematical_expression', 'Expresión matemática')], editable=False, max_length=24)),
                ('presented_count', models.PositiveIntegerField()),
                ('answered_count', models.PositiveIntegerField()),
                ('omitted_count', models.PositiveIntegerField()),
                ('mean_credit_basis_points', models.PositiveIntegerField()),
                ('difficulty_basis_points', models.PositiveIntegerField()),
                ('discrimination', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('discrimination_sample_size', models.PositiveIntegerField()),
                ('discrimination_suppressed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_id', models.CharField(editable=False, max_length=64)),
                ('selected_count', models.PositiveIntegerField()),
                ('selected_rate_basis_points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegradeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En ejecución'), ('completed', 'Completado'), ('completed_with_errors', 'Completado con errores'), ('failed', 'Falló')], default='queued', max_length=24)),
                ('reason', models.TextField(max_length=2000)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('processed_attempts', models.PositiveIntegerField(default=0)),
                ('succeeded_attempts', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('task_id', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegradeJobAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Falló'), ('skipped', 'Omitido')], default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attemptitem',
            name='candidate_position',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En curso'), ('grading_pending', 'Calificación automática pendiente'), ('pending_manual', 'Pendiente de calificación manual'), ('graded', 'Calificado'), ('grading_failed', 'Falló la calificación')], default='in_progress', max_length=24),
        ),
        migrations.AlterField(
            model_name='questionrevision',
            name='type',
            field=models.CharField(choices=[('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('true_false', 'Verdadero o falso'), ('numeric', 'Numérica'), ('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('ordering', 'Ordenamiento'), ('matching', 'Emparejamiento'), ('mathematical_expression', 'Expresión matemática')], max_length=24),
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='type',
            field=models.CharField(choices=[('single_choice', 'Selección única'), ('multiple_choice', 'Selección múltiple'), ('true_false', 'Verdadero o falso'), ('numeric', 'Numérica'), ('short_text', 'Texto corto'), ('long_text', 'Texto largo'), ('ordering', 'Ordenamiento'), ('matching', 'Emparejamiento'), ('mathematical_expression', 'Expresión matemática')], editable=False, max_length=24),
        ),
        migrations.CreateModel(
            name='AssessmentGradingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grading_policy', to='assessments.assessmentversion')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentGradingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('original', 'Original'), ('correction', 'Corrección')], max_length=16)),
                ('reason', models.TextField(blank=True, max_length=2000)),
                ('grading_snapshot', models.JSONField(editable=False)),
                ('snapshot_digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_grading_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assessments.assessmentgradingpolicy')),
                ('previous_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revision', to='assessments.assessmentgradingrevision')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='assessmentgradingpolicy',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_policy', to='assessments.assessmentgradingrevision'),
        ),
        migrations.CreateModel(
            name='AssessmentAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_size', models.PositiveIntegerField()),
                ('mean_percent_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('median_percent_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('p25_percent_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('p75_percent_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('pass_rate_basis_points', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_snapshots', to='assessments.assessmentversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_analytics_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_snapshots', to='assessments.assessmentdelivery')),
                ('grading_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_snapshots', to='assessments.assessmentgradingrevision')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsRefreshJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En ejecución'), ('completed', 'Completado'), ('completed_with_errors', 'Completado con errores'), ('failed', 'Falló')], default='queued', max_length=24)),
                ('task_id', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_jobs', to='assessments.assessmentversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_analytics_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_jobs', to='assessments.assessmentdelivery')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_analytics_jobs', to='organizations.organization')),
                ('grading_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_jobs', to='assessments.assessmentgradingrevision')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItemPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, max_length=5000)),
                ('position', models.PositiveIntegerField()),
                ('selection_count', models.PositiveIntegerField()),
                ('points_per_item', models.DecimalField(decimal_places=3, max_digits=12)),
                ('selection_strategy', models.CharField(choices=[('random_without_replacement', 'Aleatoria sin reemplazo')], default='random_without_replacement', max_length=32)),
                ('shuffle_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_item_pools_created', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_pools', to='assessments.assessmentrevision')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_item_pools_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='attemptitem',
            name='pool',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='assessments.assessmentitempool'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate_position__isnull', True), ('pool__isnull', True)), models.Q(('candidate_position__gt', 0), ('pool__isnull', False)), _connector='OR'), name='assess_attitem_pool_candidate_state'),
        ),
        migrations.AddField(
            model_name='assessmentpoolcandidate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_pool_candidates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentpoolcandidate',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='assessments.assessmentitempool'),
        ),
        migrations.AddField(
            model_name='assessmentpoolcandidate',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_candidates', to='assessments.questionversion'),
        ),
        migrations.AddField(
            model_name='attemptgradeversion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_versions', to='assessments.attempt'),
        ),
        migrations.AddField(
            model_name='attemptgradeversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_grade_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attemptgradeversion',
            name='grading_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_grades', to='assessments.assessmentgradingrevision'),
        ),
        migrations.AddField(
            model_name='attemptgradeversion',
            name='previous_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_grade', to='assessments.attemptgradeversion'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='current_grade',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_attempt', to='assessments.attemptgradeversion'),
        ),
        migrations.AddField(
            model_name='attemptgradingjob',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_jobs', to='assessments.attempt'),
        ),
        migrations.AddField(
            model_name='attemptgradingjob',
            name='grading_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_jobs', to='assessments.assessmentgradingrevision'),
        ),
        migrations.AddField(
            model_name='attemptitemgradeversion',
            name='attempt_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_grades', to='assessments.attemptgradeversion'),
        ),
        migrations.AddField(
            model_name='attemptitemgradeversion',
            name='attempt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_versions', to='assessments.attemptitem'),
        ),
        migrations.AddField(
            model_name='attemptitemgradeversion',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_grade_versions', to='assessments.response'),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_gradebooks_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='course_release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook', to='publishing.courserelease'),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_gradebooks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_gradebooks', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_gradebooks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebookcolumn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_columns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebookcolumn',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_columns', to='assessments.assessmentdelivery'),
        ),
        migrations.AddField(
            model_name='gradebookcolumn',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='assessments.coursegradebook'),
        ),
        migrations.AddField(
            model_name='gradebookcolumn',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_columns_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_entries', to='assessments.attempt'),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='attempt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_entries', to='assessments.attemptgradeversion'),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assessments.gradebookcolumn'),
        ),
        migrations.AddField(
            model_name='gradebookentry',
            name='release_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_entries', to='learning.enrollmentreleaseassignment'),
        ),
        migrations.AddField(
            model_name='gradebooksummary',
            name='gradebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='assessments.coursegradebook'),
        ),
        migrations.AddField(
            model_name='gradebooksummary',
            name='release_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook_summaries', to='learning.enrollmentreleaseassignment'),
        ),
        migrations.AddField(
            model_name='itemanalyticssnapshot',
            name='assessment_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessments.assessmentanalyticssnapshot'),
        ),
        migrations.AddField(
            model_name='itemanalyticssnapshot',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_analytics_snapshots', to='assessments.questionversion'),
        ),
        migrations.AddField(
            model_name='optionanalyticssnapshot',
            name='item_analytics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='assessments.itemanalyticssnapshot'),
        ),
        migrations.AddField(
            model_name='regradejob',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regrade_jobs', to='assessments.assessmentversion'),
        ),
        migrations.AddField(
            model_name='regradejob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_regrade_jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regradejob',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regrade_jobs', to='assessments.assessmentdelivery'),
        ),
        migrations.AddField(
            model_name='regradejob',
            name='grading_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regrade_jobs', to='assessments.assessmentgradingrevision'),
        ),
        migrations.AddField(
            model_name='regradejob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_regrade_jobs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='regradejobattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regrade_job_items', to='assessments.attempt'),
        ),
        migrations.AddField(
            model_name='regradejobattempt',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='assessments.regradejob'),
        ),
        migrations.AddField(
            model_name='regradejobattempt',
            name='new_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regrade_items_as_new', to='assessments.attemptgradeversion'),
        ),
        migrations.AddField(
            model_name='regradejobattempt',
            name='previous_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regrade_items_as_previous', to='assessments.attemptgradeversion'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgradingrevision',
            constraint=models.UniqueConstraint(fields=('policy', 'number'), name='assess_grevision_policy_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgradingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_grevision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgradingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_digest__regex', '^[0-9a-f]{64}$')), name='assess_grevision_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgradingrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', ''), ('source', 'original')), models.Q(('source', 'correction'), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='assess_grevision_reason_state'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgradingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('previous_revision__isnull', True), models.Q(('previous_revision', models.F('id')), _negated=True), _connector='OR'), name='assess_grevision_not_self'),
        ),
        migrations.AddConstraint(
            model_name='assessmentgradingpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_gpolicy_lock_positive'),
        ),
        migrations.AddIndex(
            model_name='assessmentanalyticssnapshot',
            index=models.Index(fields=['assessment_version', 'created_at'], name='assess_analytics_version_ix'),
        ),
        migrations.AddConstraint(
            model_name='assessmentanalyticssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mean_percent_basis_points__isnull', True), models.Q(('mean_percent_basis_points__gte', 0), ('mean_percent_basis_points__lte', 10000)), _connector='OR'), models.Q(('median_percent_basis_points__isnull', True), models.Q(('median_percent_basis_points__gte', 0), ('median_percent_basis_points__lte', 10000)), _connector='OR'), models.Q(('p25_percent_basis_points__isnull', True), models.Q(('p25_percent_basis_points__gte', 0), ('p25_percent_basis_points__lte', 10000)), _connector='OR'), models.Q(('p75_percent_basis_points__isnull', True), models.Q(('p75_percent_basis_points__gte', 0), ('p75_percent_basis_points__lte', 10000)), _connector='OR'), models.Q(('pass_rate_basis_points__isnull', True), models.Q(('pass_rate_basis_points__gte', 0), ('pass_rate_basis_points__lte', 10000)), _connector='OR')), name='assess_analytics_percent_ranges'),
        ),
        migrations.AddIndex(
            model_name='analyticsrefreshjob',
            index=models.Index(fields=['organization', 'status'], name='assess_analytics_job_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitempool',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('revision', 'position'), name='assess_pool_revision_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitempool',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_pool_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitempool',
            constraint=models.CheckConstraint(condition=models.Q(('selection_count__gt', 0)), name='assess_pool_selection_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitempool',
            constraint=models.CheckConstraint(condition=models.Q(('points_per_item__gt', Decimal('0'))), name='assess_pool_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentpoolcandidate',
            constraint=models.UniqueConstraint(fields=('pool', 'question_version'), name='assess_pool_candidate_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentpoolcandidate',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('pool', 'position'), name='assess_pool_candidate_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentpoolcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_pool_candidate_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.UniqueConstraint(fields=('attempt', 'number'), name='assess_grade_attempt_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('source__in', ['initial', 'regrade'])), fields=('attempt', 'grading_revision'), name='assess_grade_attempt_revision_auto_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='assess_grade_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('scoring_engine_version__gt', 0)), name='assess_grade_engine_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('automatic_score__gte', Decimal('0')), ('manual_score__gte', Decimal('0')), ('final_score__gte', Decimal('0')), ('final_score__lte', models.F('maximum_score')), ('maximum_score__gt', Decimal('0'))), name='assess_grade_scores_range'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('percent_basis_points__isnull', True), models.Q(('percent_basis_points__gte', 0), ('percent_basis_points__lte', 10000)), _connector='OR'), name='assess_grade_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('digest__regex', '^[0-9a-f]{64}$')), name='assess_grade_digest_sha256'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('previous_grade__isnull', True), models.Q(('previous_grade', models.F('id')), _negated=True), _connector='OR'), name='assess_grade_not_self'),
        ),
        migrations.AddIndex(
            model_name='attemptgradingjob',
            index=models.Index(fields=['status', 'created_at'], name='assess_gjob_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='attemptgradingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('attempt', 'grading_revision'), name='assess_gjob_one_active'),
        ),
        migrations.AddConstraint(
            model_name='attemptitemgradeversion',
            constraint=models.UniqueConstraint(fields=('attempt_grade', 'attempt_item'), name='assess_itemgrade_grade_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptitemgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('credit_basis_points__gte', 0), ('credit_basis_points__lte', 10000)), name='assess_itemgrade_credit_range'),
        ),
        migrations.AddConstraint(
            model_name='attemptitemgradeversion',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', Decimal('0')), ('score__lte', models.F('maximum_score')), ('maximum_score__gt', Decimal('0'))), name='assess_itemgrade_score_range'),
        ),
        migrations.AddConstraint(
            model_name='coursegradebook',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_gradebook_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursegradebook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('activated_by__isnull', True), ('status', 'draft')), models.Q(('activated_at__isnull', False), ('activated_by__isnull', False), ('status', 'active')), _connector='OR'), name='assess_gradebook_activation_state'),
        ),
        migrations.AddConstraint(
            model_name='gradebookcolumn',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('gradebook', 'position'), name='assess_gcolumn_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradebookcolumn',
            constraint=models.UniqueConstraint(fields=('gradebook', 'delivery'), name='assess_gcolumn_delivery_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradebookcolumn',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='assess_gcolumn_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='gradebookcolumn',
            constraint=models.CheckConstraint(condition=models.Q(('weight_basis_points__gte', 1), ('weight_basis_points__lte', 10000)), name='assess_gcolumn_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='gradebookentry',
            constraint=models.UniqueConstraint(fields=('column', 'release_assignment'), name='assess_gentry_column_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradebookentry',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', Decimal('0')), ('maximum_score__gte', Decimal('0')), ('score__lte', models.F('maximum_score'))), name='assess_gentry_score_range'),
        ),
        migrations.AddConstraint(
            model_name='gradebookentry',
            constraint=models.CheckConstraint(condition=models.Q(('percent_basis_points__isnull', True), models.Q(('percent_basis_points__gte', 0), ('percent_basis_points__lte', 10000)), _connector='OR'), name='assess_gentry_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='gradebooksummary',
            constraint=models.UniqueConstraint(fields=('gradebook', 'release_assignment'), name='assess_gsummary_book_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='gradebooksummary',
            constraint=models.CheckConstraint(condition=models.Q(('completed_columns__lte', models.F('total_columns'))), name='assess_gsummary_columns_valid'),
        ),
        migrations.AddConstraint(
            model_name='gradebooksummary',
            constraint=models.CheckConstraint(condition=models.Q(('weighted_percent_basis_points__gte', 0), ('weighted_percent_basis_points__lte', 10000)), name='assess_gsummary_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='itemanalyticssnapshot',
            constraint=models.UniqueConstraint(fields=('assessment_snapshot', 'assessment_item_id'), name='assess_itemanalytics_snapshot_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemanalyticssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('answered_count__lte', models.F('presented_count')), ('omitted_count__lte', models.F('presented_count')), ('answered_count', django.db.models.expressions.CombinedExpression(models.F('presented_count'), '-', models.F('omitted_count')))), name='assess_itemanalytics_counts_valid'),
        ),
        migrations.AddConstraint(
            model_name='itemanalyticssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('mean_credit_basis_points__gte', 0), ('mean_credit_basis_points__lte', 10000), ('difficulty_basis_points__gte', 0), ('difficulty_basis_points__lte', 10000)), name='assess_itemanalytics_bps_range'),
        ),
        migrations.AddConstraint(
            model_name='itemanalyticssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discrimination__isnull', True), ('discrimination_suppressed', True)), models.Q(('discrimination__isnull', False), ('discrimination_suppressed', False)), _connector='OR'), name='assess_itemanalytics_discrimination_state'),
        ),
        migrations.AddConstraint(
            model_name='optionanalyticssnapshot',
            constraint=models.UniqueConstraint(fields=('item_analytics', 'option_id'), name='assess_optionanalytics_item_option_unique'),
        ),
        migrations.AddConstraint(
            model_name='optionanalyticssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('selected_rate_basis_points__gte', 0), ('selected_rate_basis_points__lte', 10000)), name='assess_optionanalytics_rate_range'),
        ),
        migrations.AddIndex(
            model_name='regradejob',
            index=models.Index(fields=['organization', 'status'], name='assess_regrade_org_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='regradejob',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery__isnull', False), ('status__in', ['queued', 'running'])), fields=('organization', 'assessment_version', 'grading_revision', 'delivery'), name='assess_regrade_delivery_active'),
        ),
        migrations.AddConstraint(
            model_name='regradejob',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery__isnull', True), ('status__in', ['queued', 'running'])), fields=('organization', 'assessment_version', 'grading_revision'), name='assess_regrade_global_active'),
        ),
        migrations.AddConstraint(
            model_name='regradejob',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='assess_regrade_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='regradejob',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='assess_regrade_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='regradejob',
            constraint=models.CheckConstraint(condition=models.Q(('processed_attempts__lte', models.F('total_attempts')), ('succeeded_attempts__lte', models.F('processed_attempts')), ('failed_attempts__lte', models.F('processed_attempts'))), name='assess_regrade_counts_valid'),
        ),
        migrations.AddIndex(
            model_name='regradejobattempt',
            index=models.Index(fields=['job', 'status'], name='assess_regrade_item_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='regradejobattempt',
            constraint=models.UniqueConstraint(fields=('job', 'attempt'), name='assess_regrade_item_unique'),
        ),
    ]
