# Generated by Django 6.0.7 on 2026-07-30 23:11

import hashlib
import json
import uuid
from decimal import ROUND_FLOOR, Decimal, localcontext

from django.db import migrations

SCORING_ENGINE_VERSION = 2
LEGACY_POLICIES = {
    "single_choice": "all_or_nothing",
    "multiple_choice": "exact_set",
    "true_false": "all_or_nothing",
    "numeric": "binary_tolerance",
    "short_text": "all_or_nothing",
    "long_text": "manual",
    "ordering": "exact",
    "matching": "exact",
}


def _digest(payload):
    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _basis_points(score, maximum):
    if maximum <= 0:
        return 0
    with localcontext() as context:
        context.prec = 50
        value = (score * Decimal("10000")) / maximum
        return min(
            10000,
            max(0, int(value.to_integral_value(rounding=ROUND_FLOOR))),
        )


def _grading_snapshot(version):
    public_items = {
        str(item["id"]): item
        for section in version.public_snapshot["sections"]
        for item in section["items"]
    }
    items = []
    for entry in version.grading_snapshot["items"]:
        source_id = str(entry["assessment_item_id"])
        public_item = public_items[source_id]
        question_type = str(entry["type"])
        grading_payload = json.loads(json.dumps(entry["grading"]))
        if question_type == "multiple_choice":
            grading_payload["option_ids"] = [
                option["id"] for option in public_item["question"]["options"]
            ]
        items.append(
            {
                "source_kind": "fixed_item",
                "source_id": source_id,
                "question_version_id": str(entry["question_version_id"]),
                "question_type": question_type,
                "scoring_policy": LEGACY_POLICIES[question_type],
                "grading_payload": grading_payload,
                "maximum_score": str(public_item["points"]),
                "feedback_payload": json.loads(json.dumps(entry["feedback"])),
                "scoring_engine_version": SCORING_ENGINE_VERSION,
            }
        )
    return {
        "schema_version": 1,
        "scoring_engine_version": SCORING_ENGINE_VERSION,
        "items": items,
    }


def forwards(apps, schema_editor):
    AssessmentVersion = apps.get_model("assessments", "AssessmentVersion")
    AssessmentGradingPolicy = apps.get_model(
        "assessments", "AssessmentGradingPolicy"
    )
    AssessmentGradingRevision = apps.get_model(
        "assessments", "AssessmentGradingRevision"
    )
    Attempt = apps.get_model("assessments", "Attempt")
    AttemptGradeVersion = apps.get_model("assessments", "AttemptGradeVersion")
    AttemptItem = apps.get_model("assessments", "AttemptItem")
    AttemptItemGradeVersion = apps.get_model(
        "assessments", "AttemptItemGradeVersion"
    )
    Response = apps.get_model("assessments", "Response")

    revision_by_version = {}
    for version in AssessmentVersion.objects.order_by("created_at", "id").iterator(
        chunk_size=100
    ):
        existing = AssessmentGradingPolicy.objects.filter(
            assessment_version_id=version.id
        ).first()
        if existing is not None:
            revision_by_version[version.id] = existing.current_revision_id
            continue
        policy = AssessmentGradingPolicy.objects.create(
            id=uuid.uuid4(),
            assessment_version_id=version.id,
            lock_version=1,
        )
        snapshot = _grading_snapshot(version)
        revision = AssessmentGradingRevision.objects.create(
            id=uuid.uuid4(),
            policy_id=policy.id,
            number=1,
            previous_revision_id=None,
            source="original",
            reason="",
            grading_snapshot=snapshot,
            snapshot_digest=_digest(snapshot),
            created_by_id=version.created_by_id,
        )
        AssessmentGradingPolicy.objects.filter(id=policy.id).update(
            current_revision_id=revision.id
        )
        revision_by_version[version.id] = revision.id

    attempts = Attempt.objects.filter(
        status__in=["pending_manual", "graded"]
    ).order_by("created_at", "id")
    for attempt in attempts.iterator(chunk_size=100):
        if attempt.current_grade_id is not None:
            continue
        revision_id = revision_by_version[attempt.assessment_version_id]
        percent = attempt.basis_points
        if attempt.status == "graded" and percent is None:
            percent = _basis_points(attempt.total_score, attempt.maximum_score)
        grading_status = (
            "pending_manual" if attempt.status == "pending_manual" else "graded"
        )
        grade_payload = {
            "attempt_id": str(attempt.id),
            "number": 1,
            "previous_grade_id": None,
            "grading_revision_id": str(revision_id),
            "source": "initial",
            "scoring_engine_version": SCORING_ENGINE_VERSION,
            "automatic_score": format(attempt.auto_score, "f"),
            "manual_score": format(attempt.manual_score, "f"),
            "final_score": format(attempt.total_score, "f"),
            "maximum_score": format(attempt.maximum_score, "f"),
            "percent_basis_points": percent,
            "grading_status": grading_status,
        }
        grade = AttemptGradeVersion.objects.create(
            id=uuid.uuid4(),
            attempt_id=attempt.id,
            number=1,
            previous_grade_id=None,
            grading_revision_id=revision_id,
            source="initial",
            scoring_engine_version=SCORING_ENGINE_VERSION,
            automatic_score=attempt.auto_score,
            manual_score=attempt.manual_score,
            final_score=attempt.total_score,
            maximum_score=attempt.maximum_score,
            percent_basis_points=percent,
            passed=attempt.passed if grading_status == "graded" else None,
            grading_status=grading_status,
            digest=_digest(grade_payload),
            created_by_id=None,
        )
        responses = {
            response.attempt_item_id: response
            for response in Response.objects.filter(
                attempt_item__attempt_id=attempt.id
            )
        }
        item_grades = []
        for item in AttemptItem.objects.filter(attempt_id=attempt.id).order_by(
            "display_position"
        ):
            response = responses.get(item.id)
            score = response.score if response is not None else Decimal("0.000")
            pending = response is not None and response.status == "pending_manual"
            item_grades.append(
                AttemptItemGradeVersion(
                    id=uuid.uuid4(),
                    attempt_grade_id=grade.id,
                    attempt_item_id=item.id,
                    response_id=response.id if response is not None else None,
                    credit_basis_points=(
                        0 if pending else _basis_points(score, item.points)
                    ),
                    score=score,
                    maximum_score=item.points,
                    grading_status="pending_manual" if pending else "graded",
                    is_correct=(
                        None
                        if pending
                        else _basis_points(score, item.points) == 10000
                    ),
                    feedback_key=(
                        "manual"
                        if response is not None
                        and response.status == "manually_graded"
                        else "legacy"
                    ),
                    manual_review_reason="legacy_manual_required" if pending else "",
                )
            )
        AttemptItemGradeVersion.objects.bulk_create(item_grades, batch_size=500)
        Attempt.objects.filter(id=attempt.id).update(current_grade_id=grade.id)


def backwards(apps, schema_editor):
    Attempt = apps.get_model("assessments", "Attempt")
    AssessmentGradingPolicy = apps.get_model(
        "assessments", "AssessmentGradingPolicy"
    )
    AttemptItemGradeVersion = apps.get_model(
        "assessments", "AttemptItemGradeVersion"
    )
    AttemptGradeVersion = apps.get_model("assessments", "AttemptGradeVersion")
    AssessmentGradingRevision = apps.get_model(
        "assessments", "AssessmentGradingRevision"
    )
    Attempt.objects.update(current_grade_id=None)
    AttemptItemGradeVersion.objects.all().delete()
    AttemptGradeVersion.objects.all().delete()
    AssessmentGradingPolicy.objects.update(current_revision_id=None)
    AssessmentGradingRevision.objects.all().delete()
    AssessmentGradingPolicy.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_advanced_grading_models'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
