# Generated by Django 6.0.7 on 2026-07-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_backfill_advanced_grading'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE TRIGGER assessments_grevision_reject_update
BEFORE UPDATE ON assessments_assessmentgradingrevision
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_grevision_reject_delete
BEFORE DELETE ON assessments_assessmentgradingrevision
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();

CREATE TRIGGER assessments_grade_reject_update
BEFORE UPDATE ON assessments_attemptgradeversion
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_grade_reject_delete
BEFORE DELETE ON assessments_attemptgradeversion
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();

CREATE TRIGGER assessments_itemgrade_reject_update
BEFORE UPDATE ON assessments_attemptitemgradeversion
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_itemgrade_reject_delete
BEFORE DELETE ON assessments_attemptitemgradeversion
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();

CREATE TRIGGER assessments_analytics_reject_update
BEFORE UPDATE ON assessments_assessmentanalyticssnapshot
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_analytics_reject_delete
BEFORE DELETE ON assessments_assessmentanalyticssnapshot
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();

CREATE TRIGGER assessments_itemanalytics_reject_update
BEFORE UPDATE ON assessments_itemanalyticssnapshot
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_itemanalytics_reject_delete
BEFORE DELETE ON assessments_itemanalyticssnapshot
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();

CREATE TRIGGER assessments_optionanalytics_reject_update
BEFORE UPDATE ON assessments_optionanalyticssnapshot
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_optionanalytics_reject_delete
BEFORE DELETE ON assessments_optionanalyticssnapshot
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();

CREATE OR REPLACE FUNCTION assessments_protect_regrade_job_attempt()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' OR OLD.status IN ('completed', 'skipped') THEN
        RAISE EXCEPTION 'protected regrade job attempt: % is not allowed', TG_OP
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER assessments_regradeitem_protect_update
BEFORE UPDATE ON assessments_regradejobattempt
FOR EACH ROW EXECUTE FUNCTION assessments_protect_regrade_job_attempt();
CREATE TRIGGER assessments_regradeitem_reject_delete
BEFORE DELETE ON assessments_regradejobattempt
FOR EACH ROW EXECUTE FUNCTION assessments_protect_regrade_job_attempt();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS assessments_regradeitem_reject_delete
    ON assessments_regradejobattempt;
DROP TRIGGER IF EXISTS assessments_regradeitem_protect_update
    ON assessments_regradejobattempt;
DROP FUNCTION IF EXISTS assessments_protect_regrade_job_attempt();

DROP TRIGGER IF EXISTS assessments_optionanalytics_reject_delete
    ON assessments_optionanalyticssnapshot;
DROP TRIGGER IF EXISTS assessments_optionanalytics_reject_update
    ON assessments_optionanalyticssnapshot;
DROP TRIGGER IF EXISTS assessments_itemanalytics_reject_delete
    ON assessments_itemanalyticssnapshot;
DROP TRIGGER IF EXISTS assessments_itemanalytics_reject_update
    ON assessments_itemanalyticssnapshot;
DROP TRIGGER IF EXISTS assessments_analytics_reject_delete
    ON assessments_assessmentanalyticssnapshot;
DROP TRIGGER IF EXISTS assessments_analytics_reject_update
    ON assessments_assessmentanalyticssnapshot;
DROP TRIGGER IF EXISTS assessments_itemgrade_reject_delete
    ON assessments_attemptitemgradeversion;
DROP TRIGGER IF EXISTS assessments_itemgrade_reject_update
    ON assessments_attemptitemgradeversion;
DROP TRIGGER IF EXISTS assessments_grade_reject_delete
    ON assessments_attemptgradeversion;
DROP TRIGGER IF EXISTS assessments_grade_reject_update
    ON assessments_attemptgradeversion;
DROP TRIGGER IF EXISTS assessments_grevision_reject_delete
    ON assessments_assessmentgradingrevision;
DROP TRIGGER IF EXISTS assessments_grevision_reject_update
    ON assessments_assessmentgradingrevision;
""",
        )
    ]
