# Generated by Django 6.0.7 on 2026-08-02 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_ambiguous_legacy_bindings(apps, schema_editor):
    Delivery = apps.get_model('assessments', 'AssessmentDelivery')
    Gradebook = apps.get_model('assessments', 'CourseGradebook')
    Delivery.objects.filter(course_release__isnull=False).update(
        migration_review_required=True
    )
    Gradebook.objects.all().update(migration_review_required=True)


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_enforce_advanced_grading_immutability'),
        ('learning', '0007_activityprogress_activityprogressevent_and_more'),
        ('organizations', '0007_organization_activated_at_organization_status_and_more'),
        ('publishing', '0002_enforce_release_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentdelivery',
            name='course_group_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_deliveries', to='learning.coursegroupactivity'),
        ),
        migrations.AddField(
            model_name='assessmentdelivery',
            name='migration_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='learning.academicperiod'),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='learning.learningcohort'),
        ),
        migrations.AddField(
            model_name='coursegradebook',
            name='migration_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursegradebook',
            name='course_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='publishing.courserelease'),
        ),
        migrations.RunPython(mark_ambiguous_legacy_bindings, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='assessmentdelivery',
            index=models.Index(fields=['course_group_activity', 'status'], name='assess_del_activity_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='coursegradebook',
            constraint=models.UniqueConstraint(condition=models.Q(('course_group__isnull', False)), fields=('course_group', 'course_release', 'academic_period'), name='assess_gradebook_execution_unique'),
        ),
    ]
