# Generated by Django 6.0.7 on 2026-08-02 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_assessmentdelivery_course_group_activity_and_more'),
        ('courses', '0002_courseactivity_courseactivityavailabilityrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentActivityBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_binding', to='courses.courseactivity')),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_activity_bindings', to='assessments.assessmentversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_activity_bindings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
