# Generated by Django 6.0.7 on 2026-08-03 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessmentactivitybinding'),
        ('learning', '0007_activityprogress_activityprogressevent_and_more'),
        ('organizations', '0007_organization_activated_at_organization_status_and_more'),
        ('publishing', '0002_enforce_release_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assessmentdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('course_group_activity__isnull', False), models.Q(('status', 'withdrawn'), _negated=True)), fields=('course_group_activity',), name='assess_delivery_one_current_activity'),
        ),
    ]
