# Generated by Django 6.0.7 on 2026-08-03 11:59

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_enforce_current_delivery_per_group_activity'),
        ('assets', '0002_enforce_asset_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAssetReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(editable=False, max_length=255)),
                ('reference_role', models.CharField(editable=False, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_references', to='assets.assetversion')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_references', to='assessments.questionversion')),
            ],
            options={
                'indexes': [models.Index(fields=['asset_version', 'created_at'], name='assess_assetref_asset_time_ix')],
                'constraints': [models.UniqueConstraint(fields=('question_version', 'location'), name='assess_assetref_version_location_unique'), models.CheckConstraint(condition=models.Q(('location', django.db.models.functions.text.Trim(models.F('location'))), models.Q(('location', ''), _negated=True)), name='assess_assetref_location_trimmed'), models.CheckConstraint(condition=models.Q(('reference_role__in', ('primary', 'captions', 'choice'))), name='assess_assetref_role_valid')],
            },
        ),
        migrations.RunSQL(
            sql="""
CREATE TRIGGER assessments_assetref_reject_update
BEFORE UPDATE ON assessments_assessmentassetreference
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
CREATE TRIGGER assessments_assetref_reject_delete
BEFORE DELETE ON assessments_assessmentassetreference
FOR EACH ROW EXECUTE FUNCTION assessments_reject_immutable_change();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS assessments_assetref_reject_delete
    ON assessments_assessmentassetreference;
DROP TRIGGER IF EXISTS assessments_assetref_reject_update
    ON assessments_assessmentassetreference;
""",
        ),
    ]
