# Generated by Django 6.0.7 on 2026-08-01 05:06

import django.db.models.deletion
import django.db.models.functions.text
import domain.scheduling.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('organizations', '0004_alter_membershipevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEventSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('event_type', models.CharField(choices=[('live_class', 'Clase en vivo'), ('academic_activity', 'Actividad académica')], default='live_class', max_length=32)),
                ('timezone_name', models.CharField(max_length=64)),
                ('first_starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('rrule', models.CharField(blank=True, max_length=1000)),
                ('recurrence_count', models.PositiveSmallIntegerField(default=1)),
                ('recurrence_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada')], default='active', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_event_series', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_event_series_created', to=settings.AUTH_USER_MODEL)),
                ('host_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_event_series', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_event_series', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_event_series_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicEventOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_starts_at', models.DateTimeField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=16)),
                ('is_exception', models.BooleanField(default=False)),
                ('title_override', models.CharField(blank=True, max_length=200)),
                ('description_override', models.TextField(blank=True, max_length=2000)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='scheduling.academiceventseries')),
            ],
            options={
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(default=domain.scheduling.models.livekit_room_name, editable=False, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('live', 'En vivo'), ('ended', 'Finalizada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=16)),
                ('room_sid', models.CharField(blank=True, max_length=64)),
                ('actual_started_at', models.DateTimeField(blank=True, null=True)),
                ('actual_ended_at', models.DateTimeField(blank=True, null=True)),
                ('egress_id', models.CharField(blank=True, max_length=128)),
                ('egress_status', models.CharField(choices=[('disabled', 'Deshabilitada'), ('idle', 'Disponible'), ('starting', 'Iniciando'), ('active', 'Activa'), ('ended', 'Finalizada'), ('failed', 'Fallida')], default='disabled', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='live_session', to='scheduling.academiceventoccurrence')),
            ],
        ),
        migrations.CreateModel(
            name='LiveKitWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('event_created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='processing', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('processing_error', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='scheduling.livesession')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_identity', models.CharField(max_length=160)),
                ('participant_sid', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('host', 'Profesor'), ('student', 'Estudiante'), ('administrator', 'Administrador')], max_length=20)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('disconnect_reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_attendance_segments', to=settings.AUTH_USER_MODEL)),
                ('joined_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opened_attendance_segment', to='scheduling.livekitwebhookevent')),
                ('left_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_attendance_segments', to='scheduling.livekitwebhookevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_segments', to='scheduling.livesession')),
            ],
            options={
                'ordering': ('joined_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='academiceventseries',
            index=models.Index(fields=['organization', 'status'], name='sched_series_org_state_ix'),
        ),
        migrations.AddIndex(
            model_name='academiceventseries',
            index=models.Index(fields=['course', 'status'], name='sched_series_course_state_ix'),
        ),
        migrations.AddIndex(
            model_name='academiceventseries',
            index=models.Index(fields=['host_membership'], name='sched_series_host_ix'),
        ),
        migrations.AddConstraint(
            model_name='academiceventseries',
            constraint=models.CheckConstraint(condition=models.Q(('title', django.db.models.functions.text.Trim(models.F('title'))), models.Q(('title', ''), _negated=True)), name='sched_series_title_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='academiceventseries',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 720)), name='sched_series_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='academiceventseries',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_count__gte', 1), ('recurrence_count__lte', 366)), name='sched_series_recurrence_range'),
        ),
        migrations.AddConstraint(
            model_name='academiceventseries',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='sched_series_lock_positive'),
        ),
        migrations.AddIndex(
            model_name='academiceventoccurrence',
            index=models.Index(fields=['starts_at', 'ends_at'], name='sched_occ_window_ix'),
        ),
        migrations.AddIndex(
            model_name='academiceventoccurrence',
            index=models.Index(fields=['series', 'status', 'starts_at'], name='sched_occ_series_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='academiceventoccurrence',
            constraint=models.UniqueConstraint(fields=('series', 'original_starts_at'), name='sched_occurrence_original_unique'),
        ),
        migrations.AddConstraint(
            model_name='academiceventoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='sched_occurrence_window'),
        ),
        migrations.AddConstraint(
            model_name='academiceventoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='sched_occurrence_lock_positive'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status'], name='sched_live_state_ix'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['room_sid'], name='sched_live_sid_ix'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='sched_live_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_ended_at__isnull', True), ('status', 'scheduled')), models.Q(('actual_ended_at__isnull', True), ('actual_started_at__isnull', False), ('status', 'live')), models.Q(('actual_ended_at__isnull', False), ('actual_started_at__isnull', False), ('status', 'ended')), models.Q(('actual_ended_at__isnull', False), ('status', 'cancelled')), _connector='OR'), name='sched_live_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='livekitwebhookevent',
            index=models.Index(fields=['event_type', 'event_created_at'], name='sched_hook_type_time_ix'),
        ),
        migrations.AddIndex(
            model_name='livekitwebhookevent',
            index=models.Index(fields=['processing_status', 'received_at'], name='sched_hook_state_time_ix'),
        ),
        migrations.AddIndex(
            model_name='attendancesegment',
            index=models.Index(fields=['session', 'joined_at'], name='sched_att_session_ix'),
        ),
        migrations.AddIndex(
            model_name='attendancesegment',
            index=models.Index(fields=['user', 'joined_at'], name='sched_att_user_ix'),
        ),
        migrations.AddIndex(
            model_name='attendancesegment',
            index=models.Index(fields=['participant_identity', 'joined_at'], name='sched_att_identity_ix'),
        ),
        migrations.AddIndex(
            model_name='attendancesegment',
            index=models.Index(fields=['participant_sid', 'left_at'], name='sched_att_sid_ix'),
        ),
        migrations.AddConstraint(
            model_name='attendancesegment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_seconds__isnull', True), ('left_at__isnull', True)), models.Q(('duration_seconds__isnull', False), ('left_at__isnull', False)), _connector='OR'), name='sched_attendance_close_state'),
        ),
        migrations.AddConstraint(
            model_name='attendancesegment',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='sched_attendance_time_order'),
        ),
    ]
