# Generated by Django 6.0.7 on 2026-08-01 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('organizations', '0004_alter_membershipevent_event_type'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='academiceventseries',
            name='attendance_threshold_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academiceventseries',
            name='counts_toward_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academiceventseries',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_event_series', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='academiceventseries',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attendance_threshold_minutes__isnull', True), ('counts_toward_progress', False)), models.Q(('attendance_threshold_minutes__gte', 1), ('attendance_threshold_minutes__lte', 720), ('counts_toward_progress', True), ('course__isnull', False)), _connector='OR'), name='sched_series_progress_configuration'),
        ),
        migrations.AddField(
            model_name='academiceventparticipant',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_event_participants_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academiceventparticipant',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_event_participations', to='organizations.membership'),
        ),
        migrations.AddField(
            model_name='academiceventparticipant',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='scheduling.academiceventseries'),
        ),
        migrations.AddIndex(
            model_name='academiceventparticipant',
            index=models.Index(fields=['membership', 'series'], name='sched_participant_member_ix'),
        ),
        migrations.AddConstraint(
            model_name='academiceventparticipant',
            constraint=models.UniqueConstraint(fields=('series', 'membership'), name='sched_series_participant_unique'),
        ),
    ]
