# Generated by Django 6.0.7 on 2026-08-01 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('learning', '0006_cohortstaffassignment_enrollmentcohortassignment_and_more'),
        ('organizations', '0006_alter_membershipevent_event_type'),
        ('scheduling', '0003_alter_livekitwebhookevent_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academiceventseries',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_event_series', to='learning.learningcohort'),
        ),
        migrations.AddIndex(
            model_name='academiceventseries',
            index=models.Index(fields=['course_group', 'status'], name='sched_series_group_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='academiceventseries',
            constraint=models.CheckConstraint(condition=models.Q(('course_group__isnull', True), ('course__isnull', False), _connector='OR'), name='sched_series_group_requires_course'),
        ),
    ]
