# Generated by Django 6.0.7 on 2026-08-02 01:39

import django.db.models.deletion
from django.db import migrations, models


def mark_ambiguous_legacy_series(apps, schema_editor):
    Series = apps.get_model('scheduling', 'AcademicEventSeries')
    Series.objects.filter(course__isnull=False).update(
        migration_review_required=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_activityprogress_activityprogressevent_and_more'),
        ('scheduling', '0004_course_group_scoped_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiceventseries',
            name='course_group_activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_event_series', to='learning.coursegroupactivity'),
        ),
        migrations.AddField(
            model_name='academiceventseries',
            name='migration_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_ambiguous_legacy_series, migrations.RunPython.noop),
    ]
