# Generated by Django 6.0.7 on 2026-08-02 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseactivity_courseactivityavailabilityrule_and_more'),
        ('scheduling', '0005_academiceventseries_course_group_activity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassActivityBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_attended_occurrences', models.PositiveSmallIntegerField(default=1)),
                ('minimum_attendance_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='live_class_binding', to='courses.courseactivity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_class_activity_bindings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_attended_occurrences__gt', 0)), name='sched_binding_occurrences_positive'), models.CheckConstraint(condition=models.Q(('minimum_attendance_minutes__isnull', True), ('minimum_attendance_minutes__gt', 0), _connector='OR'), name='sched_binding_minutes_positive')],
            },
        ),
    ]
