# Generated by Django 6.0.7 on 2026-08-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_activity_contributions(apps, schema_editor):
    AcademicEventSeries = apps.get_model("scheduling", "AcademicEventSeries")
    AcademicEventSeries.objects.filter(course_group_activity_id__isnull=False).update(
        activity_progress_contribution=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_courseteachingexception"),
        ("learning", "0007_activityprogress_activityprogressevent_and_more"),
        (
            "organizations",
            "0007_organization_activated_at_organization_status_and_more",
        ),
        ("scheduling", "0006_liveclassactivitybinding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academiceventseries",
            name="activity_progress_contribution",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="academiceventseries",
            name="course_group_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="live_event_series_set",
                to="learning.coursegroupactivity",
            ),
        ),
        migrations.RunPython(
            preserve_existing_activity_contributions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="academiceventseries",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("course_group_activity__isnull", False),
                    ("activity_progress_contribution", False),
                    _connector="OR",
                ),
                name="sched_series_activity_contribution_scope",
            ),
        ),
    ]
