# Generated by Django 6.0.7 on 2026-08-02 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseteachingexception'),
        ('scheduling', '0007_academiceventseries_activity_progress_contribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='join_after_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='join_before_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='recording_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('speaker', 'Speaker')], default='speaker', max_length=16),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='recording_mode',
            field=models.CharField(choices=[('off', 'Off'), ('manual', 'Manual'), ('automatic', 'Automatic')], default='off', max_length=16),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='room_departure_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='room_empty_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='session_mode',
            field=models.CharField(choices=[('interactive', 'Interactive'), ('webinar', 'Webinar')], default='interactive', max_length=16),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='student_audio_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='student_screen_share_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='student_video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='liveclassactivitybinding',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__gte', 2), ('max_participants__lte', 1000)), name='sched_binding_max_participants_range'),
        ),
        migrations.AddConstraint(
            model_name='liveclassactivitybinding',
            constraint=models.CheckConstraint(condition=models.Q(('room_empty_timeout_seconds__gte', 60), ('room_empty_timeout_seconds__lte', 3600)), name='sched_binding_empty_timeout_range'),
        ),
        migrations.AddConstraint(
            model_name='liveclassactivitybinding',
            constraint=models.CheckConstraint(condition=models.Q(('room_departure_timeout_seconds__lte', 600)), name='sched_binding_departure_timeout_range'),
        ),
        migrations.AddConstraint(
            model_name='liveclassactivitybinding',
            constraint=models.CheckConstraint(condition=models.Q(('join_before_minutes__lte', 120)), name='sched_binding_join_before_range'),
        ),
        migrations.AddConstraint(
            model_name='liveclassactivitybinding',
            constraint=models.CheckConstraint(condition=models.Q(('join_after_minutes__lte', 120)), name='sched_binding_join_after_range'),
        ),
    ]
