# Generated by Django 6.0.7 on 2026-08-03 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_liveclassactivitybinding_chat_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRecordingAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_acknowledgements', to='scheduling.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_recording_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='sched_recording_ack_session_user_unique')],
            },
        ),
    ]
