# Generated by Django 6.0.7 on 2026-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_liveclassactivitybinding_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassactivitybinding',
            name='recording_resolution',
            field=models.CharField(choices=[('720p', '720p'), ('1080p', '1080p')], default='1080p', max_length=8),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_layout',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_resolution',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='liveclassactivitybinding',
            name='recording_layout',
            field=models.CharField(choices=[('screen_share', 'Screen share only'), ('grid', 'Grid'), ('speaker', 'Speaker')], default='screen_share', max_length=16),
        ),
    ]
