# Generated by Django 6.0.7 on 2026-08-03 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_automatic_recording(apps, schema_editor):
    del schema_editor
    live_class_activity_binding = apps.get_model(
        "scheduling", "LiveClassActivityBinding"
    )
    live_class_activity_binding.objects.filter(recording_mode="automatic").update(
        recording_mode="manual"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_liveclassactivitybinding_recording_resolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_automatic_recording, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='liveclassactivitybinding',
            name='recording_mode',
            field=models.CharField(choices=[('off', 'Off'), ('manual', 'Manual')], default='off', max_length=16),
        ),
        migrations.CreateModel(
            name='LiveSessionRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('egress_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('disabled', 'Deshabilitada'), ('idle', 'Disponible'), ('starting', 'Iniciando'), ('active', 'Activa'), ('ended', 'Finalizada'), ('failed', 'Fallida')], default='starting', max_length=16)),
                ('layout', models.CharField(choices=[('screen_share', 'Screen share only'), ('grid', 'Grid'), ('speaker', 'Speaker')], max_length=16)),
                ('resolution', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p')], max_length=8)),
                ('filepath', models.CharField(max_length=255)),
                ('failure_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to='scheduling.livesession')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_recordings_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('started_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('starting', 'active'))), fields=('session',), name='sched_one_active_recording_per_session')],
            },
        ),
    ]
