# Generated by Django 6.0.7 on 2026-08-01 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_membershipevent_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_workspace', 'Google Workspace'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek')], max_length=32)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectada'), ('connecting', 'Conectando'), ('connected', 'Conectada'), ('degraded', 'Degradada'), ('revoked', 'Revocada')], default='disconnected', max_length=16)),
                ('auth_type', models.CharField(choices=[('oauth2_user', 'OAuth 2.0 de usuario'), ('api_key', 'Clave API')], max_length=16)),
                ('account_label', models.CharField(blank=True, max_length=160)),
                ('capabilities', models.JSONField(default=list)),
                ('granted_scopes', models.JSONField(default=list)),
                ('allowed_models', models.JSONField(default=list)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=64)),
                ('nonce', models.BinaryField(max_length=12)),
                ('ciphertext', models.BinaryField()),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credential', to='integrations.integrationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_events', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integrations.integrationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En ejecución'), ('succeeded', 'Exitosa'), ('failed', 'Fallida')], default='queued', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('capabilities', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_checks', to='integrations.integrationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('verifier_key_id', models.CharField(max_length=64)),
                ('verifier_nonce', models.BinaryField(max_length=12)),
                ('verifier_ciphertext', models.BinaryField()),
                ('requested_capabilities', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_requests', to='integrations.integrationconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_authorization_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['organization', 'status'], name='integration_org_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='integrations_one_connection_per_provider'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['connection', '-created_at'], name='integration_event_created_ix'),
        ),
        migrations.AddIndex(
            model_name='integrationhealthcheck',
            index=models.Index(fields=['connection', '-created_at'], name='health_connection_created_ix'),
        ),
        migrations.AddIndex(
            model_name='oauthauthorizationrequest',
            index=models.Index(fields=['connection', 'expires_at'], name='oauth_connection_expiry_ix'),
        ),
    ]
