# Generated by Django 6.0.7 on 2026-07-30 09:19

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('organizations', '0001_initial'),
        ('publishing', '0002_enforce_release_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('revoked', 'Revocada')], default='active', max_length=16)),
                ('access_starts_at', models.DateTimeField(blank=True, null=True)),
                ('access_ends_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField()),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to='organizations.organization')),
                ('status_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments_status_changed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentReleaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('initial', 'Asignación inicial'), ('manual_upgrade', 'Upgrade manual'), ('re_enrollment', 'Reincorporación')], max_length=24)),
                ('assigned_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='release_assignments_ended', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_assignments', to='learning.courseenrollment')),
                ('previous_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_assignment', to='learning.enrollmentreleaseassignment')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_assignments', to='publishing.courserelease')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='not_started', max_length=16)),
                ('total_units', models.PositiveIntegerField()),
                ('completed_units', models.PositiveIntegerField(default=0)),
                ('percent_basis_points', models.PositiveIntegerField(default=0)),
                ('last_unit_id', models.UUIDField(blank=True, null=True)),
                ('last_node_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lock_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='learning.enrollmentreleaseassignment')),
            ],
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='current_release_assignment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_enrollments', to='learning.enrollmentreleaseassignment'),
        ),
        migrations.CreateModel(
            name='LearningCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=16)),
                ('access_starts_at', models.DateTimeField(blank=True, null=True)),
                ('access_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_cohorts_archived', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_cohorts', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_cohorts_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_cohorts', to='organizations.organization')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_cohorts', to='publishing.courserelease')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_cohorts_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='learning.learningcohort'),
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('node_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('enrollment_created', 'Matrícula creada'), ('enrollment_suspended', 'Matrícula suspendida'), ('enrollment_reactivated', 'Matrícula reactivada'), ('enrollment_revoked', 'Matrícula revocada'), ('release_assigned', 'Release asignado'), ('release_upgraded', 'Release actualizado'), ('course_started', 'Curso iniciado'), ('course_completed', 'Curso completado'), ('course_reopened', 'Curso reabierto'), ('unit_opened', 'Unidad abierta'), ('unit_completed', 'Unidad completada'), ('unit_reopened', 'Unidad reabierta')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('course_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='learning.courseprogress')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='learning.courseenrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_events', to='organizations.organization')),
                ('release_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='learning.enrollmentreleaseassignment')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UnitProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField()),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('completed', 'Completada')], default='in_progress', max_length=16)),
                ('first_opened_at', models.DateTimeField()),
                ('last_opened_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_node_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_progress', to='learning.courseprogress')),
            ],
        ),
        migrations.AddIndex(
            model_name='enrollmentreleaseassignment',
            index=models.Index(fields=['enrollment', 'ended_at'], name='learn_assign_enroll_end_ix'),
        ),
        migrations.AddIndex(
            model_name='enrollmentreleaseassignment',
            index=models.Index(fields=['release'], name='learn_assign_release_ix'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentreleaseassignment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'sequence'), name='learning_assignment_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentreleaseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('enrollment',), name='learning_assignment_one_active'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentreleaseassignment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='learning_assignment_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentreleaseassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('ended_by__isnull', True)), models.Q(('ended_at__isnull', False), ('ended_by__isnull', False)), _connector='OR'), name='learning_assignment_end_state'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentreleaseassignment',
            constraint=models.CheckConstraint(condition=models.Q(('previous_assignment__isnull', True), models.Q(('previous_assignment', models.F('id')), _negated=True), _connector='OR'), name='learning_assignment_not_self_previous'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['status'], name='learn_progress_state_ix'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['last_activity_at'], name='learn_progress_activity_ix'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['completed_at'], name='learn_progress_complete_ix'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(('total_units__gt', 0)), name='learning_progress_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(('completed_units__gte', 0), ('completed_units__lte', models.F('total_units'))), name='learning_progress_completed_range'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(('percent_basis_points__gte', 0), ('percent_basis_points__lte', 10000)), name='learning_progress_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='learning_progress_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_units', 0), ('percent_basis_points', 0), ('started_at__isnull', True), ('status', 'not_started')), models.Q(('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('completed_units', models.F('total_units')), ('percent_basis_points', 10000), ('started_at__isnull', False), ('status', 'completed')), _connector='OR'), name='learning_progress_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='learningcohort',
            index=models.Index(fields=['organization', 'status'], name='learn_cohort_org_state_ix'),
        ),
        migrations.AddIndex(
            model_name='learningcohort',
            index=models.Index(fields=['course', 'status'], name='learn_cohort_course_state_ix'),
        ),
        migrations.AddIndex(
            model_name='learningcohort',
            index=models.Index(fields=['release'], name='learn_cohort_release_ix'),
        ),
        migrations.AddConstraint(
            model_name='learningcohort',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('course'), name='learning_cohort_course_slug_ci'),
        ),
        migrations.AddConstraint(
            model_name='learningcohort',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='learning_cohort_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='learningcohort',
            constraint=models.CheckConstraint(condition=models.Q(('name', django.db.models.functions.text.Trim(models.F('name'))), models.Q(('name', ''), _negated=True)), name='learning_cohort_name_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='learningcohort',
            constraint=models.CheckConstraint(condition=models.Q(('access_starts_at__isnull', True), ('access_ends_at__isnull', True), ('access_starts_at__lt', models.F('access_ends_at')), _connector='OR'), name='learning_cohort_access_window'),
        ),
        migrations.AddConstraint(
            model_name='learningcohort',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived')), _connector='OR'), name='learning_cohort_archive_state'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['organization', 'status'], name='learn_enroll_org_state_ix'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['membership', 'status'], name='learn_enroll_member_state_ix'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'status'], name='learn_enroll_course_state_ix'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['cohort', 'status'], name='learn_enroll_cohort_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'revoked'), _negated=True), fields=('membership', 'course'), name='learning_one_current_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='learning_enrollment_lock_positive'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('access_starts_at__isnull', True), ('access_ends_at__isnull', True), ('access_starts_at__lt', models.F('access_ends_at')), _connector='OR'), name='learning_enrollment_access_window'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active'), ('suspended_at__isnull', True)), models.Q(('revoked_at__isnull', True), ('status', 'suspended'), ('suspended_at__isnull', False)), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='learning_enrollment_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['enrollment', 'occurred_at'], name='learn_event_enroll_time_ix'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['course_progress', 'occurred_at'], name='learn_event_progress_time_ix'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='learn_event_type_time_ix'),
        ),
        migrations.AddIndex(
            model_name='unitprogress',
            index=models.Index(fields=['course_progress', 'status'], name='learn_unit_progress_state_ix'),
        ),
        migrations.AddIndex(
            model_name='unitprogress',
            index=models.Index(fields=['last_opened_at'], name='learn_unit_last_open_ix'),
        ),
        migrations.AddConstraint(
            model_name='unitprogress',
            constraint=models.UniqueConstraint(fields=('course_progress', 'unit_id'), name='learning_unit_progress_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='learning_unit_progress_lifecycle'),
        ),
    ]
