# Generated by Django 6.0.7 on 2026-07-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION learning_reject_event_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'immutable learning event: % is not allowed', TG_OP
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER learning_event_reject_update
BEFORE UPDATE ON learning_learningevent
FOR EACH ROW EXECUTE FUNCTION learning_reject_event_change();

CREATE TRIGGER learning_event_reject_delete
BEFORE DELETE ON learning_learningevent
FOR EACH ROW EXECUTE FUNCTION learning_reject_event_change();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS learning_event_reject_delete
    ON learning_learningevent;
DROP TRIGGER IF EXISTS learning_event_reject_update
    ON learning_learningevent;
DROP FUNCTION IF EXISTS learning_reject_event_change();
""",
        )
    ]
