# Generated by Django 6.0.7 on 2026-08-01 07:28

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('learning', '0003_enforce_cohort_release_immutability'),
        ('organizations', '0004_alter_membershipevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLearningRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=48)),
                ('source_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRequirementCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField()),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='courseprogress',
            name='learning_progress_lifecycle',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_required_activities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='total_required_activities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('enrollment_created', 'Matrícula creada'), ('enrollment_suspended', 'Matrícula suspendida'), ('enrollment_reactivated', 'Matrícula reactivada'), ('enrollment_revoked', 'Matrícula revocada'), ('release_assigned', 'Release asignado'), ('release_upgraded', 'Release actualizado'), ('course_started', 'Curso iniciado'), ('course_completed', 'Curso completado'), ('course_reopened', 'Curso reabierto'), ('unit_opened', 'Unidad abierta'), ('unit_completed', 'Unidad completada'), ('unit_reopened', 'Unidad reabierta'), ('requirement_completed', 'Requisito externo completado')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(('completed_required_activities__gte', 0), ('completed_required_activities__lte', models.F('total_required_activities'))), name='learn_progress_required_range'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_required_activities', 0), ('completed_units', 0), ('percent_basis_points', 0), ('started_at__isnull', True), ('status', 'not_started')), models.Q(('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('completed_required_activities', models.F('total_required_activities')), ('completed_units', models.F('total_units')), ('percent_basis_points', 10000), ('started_at__isnull', False), ('status', 'completed')), _connector='OR'), name='learning_progress_lifecycle'),
        ),
        migrations.AddField(
            model_name='externallearningrequirement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_learning_requirements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='externallearningrequirement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_learning_requirements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externallearningrequirement',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_learning_requirements_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externallearningrequirement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_learning_requirements', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='external_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='learning.externallearningrequirement'),
        ),
        migrations.AddField(
            model_name='externalrequirementcompletion',
            name='completed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_requirement_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalrequirementcompletion',
            name='course_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_requirement_completions', to='learning.courseprogress'),
        ),
        migrations.AddField(
            model_name='externalrequirementcompletion',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='learning.externallearningrequirement'),
        ),
        migrations.AddIndex(
            model_name='externallearningrequirement',
            index=models.Index(fields=['course', 'is_active'], name='learn_external_req_course_ix'),
        ),
        migrations.AddConstraint(
            model_name='externallearningrequirement',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='learn_external_requirement_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='externallearningrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('title', django.db.models.functions.text.Trim(models.F('title'))), models.Q(('title', ''), _negated=True)), name='learn_external_requirement_title_trimmed'),
        ),
        migrations.AddConstraint(
            model_name='externallearningrequirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False)), _connector='OR'), name='learn_external_requirement_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='externalrequirementcompletion',
            index=models.Index(fields=['course_progress', 'completed_at'], name='learn_external_completion_ix'),
        ),
        migrations.AddConstraint(
            model_name='externalrequirementcompletion',
            constraint=models.UniqueConstraint(fields=('requirement', 'course_progress'), name='learn_external_completion_unique'),
        ),
    ]
