# Generated by Django 6.0.7 on 2026-08-01 10:13

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_externallearningrequirement_and_more'),
        ('organizations', '0005_colombian_member_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('early_childhood', 'Primera infancia'), ('preschool', 'Preescolar'), ('transition', 'Transición'), ('primary_1', 'Primero'), ('primary_2', 'Segundo'), ('primary_3', 'Tercero'), ('primary_4', 'Cuarto'), ('primary_5', 'Quinto'), ('secondary_6', 'Sexto'), ('secondary_7', 'Séptimo'), ('secondary_8', 'Octavo'), ('secondary_9', 'Noveno'), ('secondary_10', 'Décimo'), ('secondary_11', 'Undécimo'), ('technical', 'Técnico o tecnológico'), ('higher_education', 'Educación superior'), ('continuing_education', 'Educación continua'), ('other', 'Otro')], max_length=32)),
                ('section', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_groups_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_groups', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='learningcohort',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_cohorts', to='learning.academicgroup'),
        ),
        migrations.CreateModel(
            name='AcademicGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('learner', 'Estudiante'), ('instructor', 'Docente'), ('assistant', 'Acompañante')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_group_members_added', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='learning.academicgroup')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_groups', to='organizations.membership')),
            ],
        ),
        migrations.AddIndex(
            model_name='academicgroup',
            index=models.Index(fields=['organization', 'academic_year', 'status'], name='learn_group_org_year_ix'),
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('organization'), name='learning_group_org_slug_ci'),
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.CheckConstraint(condition=models.Q(('slug', django.db.models.functions.text.Lower(models.F('slug')))), name='learning_group_slug_lowercase'),
        ),
        migrations.AddConstraint(
            model_name='academicgroup',
            constraint=models.CheckConstraint(condition=models.Q(('academic_year__gte', 2000), ('academic_year__lte', 2200)), name='learning_group_academic_year'),
        ),
        migrations.AddIndex(
            model_name='academicgroupmember',
            index=models.Index(fields=['group', 'role', 'status'], name='learn_group_roster_ix'),
        ),
        migrations.AddConstraint(
            model_name='academicgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'membership'), name='learning_group_member_unique'),
        ),
    ]
