# Generated by Django 6.0.7 on 2026-08-01 22:40

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_historical_course_group_assignments(apps, schema_editor):
    Enrollment = apps.get_model("learning", "CourseEnrollment")
    Cohort = apps.get_model("learning", "LearningCohort")
    Assignment = apps.get_model("learning", "EnrollmentCohortAssignment")
    RosterEvent = apps.get_model("learning", "RosterEvent")
    windows = {
        cohort_id: (starts_at, ends_at)
        for cohort_id, starts_at, ends_at in Cohort.objects.values_list(
            "id", "access_starts_at", "access_ends_at"
        )
    }
    for enrollment in Enrollment.objects.exclude(cohort__isnull=True).iterator():
        starts_at, ends_at = windows[enrollment.cohort_id]
        window_mode = (
            "inherit"
            if (enrollment.access_starts_at, enrollment.access_ends_at)
            == (starts_at, ends_at)
            else "individual"
        )
        Enrollment.objects.filter(pk=enrollment.pk).update(
            access_provenance="legacy_migration",
            access_window_mode=window_mode,
        )
        Assignment.objects.create(
            enrollment_id=enrollment.pk,
            cohort_id=enrollment.cohort_id,
            source="legacy_migration",
            reason="Migración compatible desde CourseEnrollment.cohort",
            started_by_id=enrollment.created_by_id,
            started_at=enrollment.created_at,
        )
        RosterEvent.objects.create(
            organization_id=enrollment.organization_id,
            cohort_id=enrollment.cohort_id,
            event_type="legacy_backfilled",
            actor_id=enrollment.created_by_id,
            occurred_at=enrollment.created_at,
            details={"enrollment_id": str(enrollment.pk)},
        )


def enforce_historical_course_group_integrity(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION learning_validate_active_cohort_assignment()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.ended_at IS NULL AND NOT EXISTS (
                    SELECT 1
                    FROM learning_courseenrollment AS enrollment
                    JOIN learning_learningcohort AS cohort ON cohort.id = NEW.cohort_id
                    JOIN learning_enrollmentreleaseassignment AS release_assignment
                      ON release_assignment.id = enrollment.current_release_assignment_id
                    WHERE enrollment.id = NEW.enrollment_id
                      AND enrollment.organization_id = cohort.organization_id
                      AND enrollment.course_id = cohort.course_id
                      AND release_assignment.release_id = cohort.release_id
                      AND release_assignment.ended_at IS NULL
                ) THEN
                    RAISE EXCEPTION 'active course-group assignment must match organization, course and effective release'
                    USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE FUNCTION learning_validate_cohort_staff_assignment()
            RETURNS trigger AS $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM learning_learningcohort AS cohort
                    JOIN organizations_membership AS membership ON membership.id = NEW.membership_id
                    WHERE cohort.id = NEW.cohort_id
                      AND cohort.organization_id = membership.organization_id
                ) THEN
                    RAISE EXCEPTION 'course-group staff must belong to the same organization'
                    USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE FUNCTION learning_prevent_closed_assignment_mutation()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'historical roster rows cannot be deleted'
                    USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                IF OLD.ended_at IS NOT NULL THEN
                    RAISE EXCEPTION 'closed roster rows are immutable'
                    USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                IF NEW.ended_at IS NULL OR NEW.ended_by_id IS NULL THEN
                    RAISE EXCEPTION 'active roster rows can only be closed'
                    USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                IF (to_jsonb(NEW) - ARRAY['ended_at', 'ended_by_id'])
                   <> (to_jsonb(OLD) - ARRAY['ended_at', 'ended_by_id']) THEN
                    RAISE EXCEPTION 'roster history fields are immutable'
                    USING ERRCODE = 'integrity_constraint_violation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE OR REPLACE FUNCTION learning_prevent_roster_event_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'roster events are append-only'
                USING ERRCODE = 'integrity_constraint_violation';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER learning_validate_active_cohort_assignment_trigger
            BEFORE INSERT OR UPDATE ON learning_enrollmentcohortassignment
            FOR EACH ROW EXECUTE FUNCTION learning_validate_active_cohort_assignment();

            CREATE TRIGGER learning_validate_cohort_staff_assignment_trigger
            BEFORE INSERT OR UPDATE ON learning_cohortstaffassignment
            FOR EACH ROW EXECUTE FUNCTION learning_validate_cohort_staff_assignment();

            CREATE TRIGGER learning_immutable_cohort_assignment_trigger
            BEFORE UPDATE OR DELETE ON learning_enrollmentcohortassignment
            FOR EACH ROW EXECUTE FUNCTION learning_prevent_closed_assignment_mutation();

            CREATE TRIGGER learning_immutable_cohort_staff_trigger
            BEFORE UPDATE OR DELETE ON learning_cohortstaffassignment
            FOR EACH ROW EXECUTE FUNCTION learning_prevent_closed_assignment_mutation();

            CREATE TRIGGER learning_immutable_roster_event_trigger
            BEFORE UPDATE OR DELETE ON learning_rosterevent
            FOR EACH ROW EXECUTE FUNCTION learning_prevent_roster_event_mutation();
            """
        )


def remove_historical_course_group_integrity(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DROP TRIGGER IF EXISTS learning_validate_active_cohort_assignment_trigger
              ON learning_enrollmentcohortassignment;
            DROP TRIGGER IF EXISTS learning_validate_cohort_staff_assignment_trigger
              ON learning_cohortstaffassignment;
            DROP TRIGGER IF EXISTS learning_immutable_cohort_assignment_trigger
              ON learning_enrollmentcohortassignment;
            DROP TRIGGER IF EXISTS learning_immutable_cohort_staff_trigger
              ON learning_cohortstaffassignment;
            DROP TRIGGER IF EXISTS learning_immutable_roster_event_trigger
              ON learning_rosterevent;
            DROP FUNCTION IF EXISTS learning_validate_active_cohort_assignment();
            DROP FUNCTION IF EXISTS learning_validate_cohort_staff_assignment();
            DROP FUNCTION IF EXISTS learning_prevent_closed_assignment_mutation();
            DROP FUNCTION IF EXISTS learning_prevent_roster_event_mutation();
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("learning", "0005_academicgroup_learningcohort_academic_group_and_more"),
        ("organizations", "0006_alter_membershipevent_event_type"),
        ("publishing", "0002_enforce_release_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortStaffAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead_instructor", "Docente principal"),
                            ("instructor", "Docente"),
                            ("assistant", "Asistente"),
                        ],
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentCohortAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Asignación manual"),
                            (
                                "academic_group_sync",
                                "Sincronización de grupo académico",
                            ),
                            ("legacy_migration", "Migración compatible"),
                            ("transfer", "Traslado"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RosterEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("academic_group_roster_replaced", "Padrón actualizado"),
                            ("course_group_created", "Grupo de curso creado"),
                            ("course_group_synced", "Roster sincronizado"),
                            ("enrollment_assigned", "Matrícula asignada al grupo"),
                            ("enrollment_unassigned", "Matrícula retirada del grupo"),
                            ("staff_assigned", "Docente asignado"),
                            ("staff_unassigned", "Docente retirado"),
                            ("legacy_backfilled", "Historial compatible creado"),
                        ],
                        max_length=48,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("details", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="academicgroup",
            name="lock_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="access_provenance",
            field=models.CharField(
                choices=[
                    ("manual", "Asignación manual"),
                    ("academic_group_sync", "Sincronización de grupo académico"),
                    ("legacy_migration", "Migración compatible"),
                    ("transfer", "Traslado"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="access_window_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Hereda la política del grupo de curso"),
                    ("individual", "Excepción individual"),
                ],
                default="individual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="learningcohort",
            name="lock_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="learningcohort",
            name="roster_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("synced", "Sincronizado con grupo académico"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="academicgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gt", 0)),
                name="learning_group_lock_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningcohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gt", 0)),
                name="learning_cohort_lock_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningcohort",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("roster_mode", "manual"),
                    ("academic_group__isnull", False),
                    _connector="OR",
                ),
                name="learning_synced_cohort_needs_group",
            ),
        ),
        migrations.AddField(
            model_name="cohortstaffassignment",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_assignments",
                to="learning.learningcohort",
            ),
        ),
        migrations.AddField(
            model_name="cohortstaffassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_staff_assignments_ended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cohortstaffassignment",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_group_staff_assignments",
                to="organizations.membership",
            ),
        ),
        migrations.AddField(
            model_name="cohortstaffassignment",
            name="started_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_staff_assignments_started",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollmentcohortassignment",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollment_assignments",
                to="learning.learningcohort",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentcohortassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollment_cohort_assignments_ended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollmentcohortassignment",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_assignments",
                to="learning.courseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentcohortassignment",
            name="started_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollment_cohort_assignments_started",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rosterevent",
            name="academic_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roster_events",
                to="learning.academicgroup",
            ),
        ),
        migrations.AddField(
            model_name="rosterevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learning_roster_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rosterevent",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roster_events",
                to="learning.learningcohort",
            ),
        ),
        migrations.AddField(
            model_name="rosterevent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learning_roster_events",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="cohortstaffassignment",
            index=models.Index(
                fields=["membership", "ended_at"], name="learn_cohort_staff_member_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="cohortstaffassignment",
            index=models.Index(
                fields=["cohort", "ended_at"], name="learn_cohort_staff_cohort_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortstaffassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("cohort", "membership"),
                name="learn_cohort_staff_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortstaffassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ended_at__isnull", True), ("ended_by__isnull", True)),
                    models.Q(("ended_at__isnull", False), ("ended_by__isnull", False)),
                    _connector="OR",
                ),
                name="learn_cohort_staff_end_state",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentcohortassignment",
            index=models.Index(
                fields=["cohort", "ended_at"], name="learn_enroll_group_cohort_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentcohortassignment",
            index=models.Index(
                fields=["enrollment", "started_at"], name="learn_enroll_group_hist_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentcohortassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("enrollment",),
                name="learn_enroll_group_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentcohortassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ended_at__isnull", True), ("ended_by__isnull", True)),
                    models.Q(("ended_at__isnull", False), ("ended_by__isnull", False)),
                    _connector="OR",
                ),
                name="learn_enroll_group_end_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentcohortassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason",
                        django.db.models.functions.text.Trim(models.F("reason")),
                    ),
                    models.Q(("reason", ""), _negated=True),
                ),
                name="learn_enroll_group_reason_trimmed",
            ),
        ),
        migrations.AddIndex(
            model_name="rosterevent",
            index=models.Index(
                fields=["organization", "occurred_at"], name="learn_roster_event_org_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="rosterevent",
            index=models.Index(
                fields=["cohort", "occurred_at"], name="learn_roster_event_cohort_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("academic_group__isnull", False),
                    ("cohort__isnull", False),
                    _connector="OR",
                ),
                name="learning_roster_event_has_target",
            ),
        ),
        migrations.RunPython(
            backfill_historical_course_group_assignments,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            enforce_historical_course_group_integrity,
            remove_historical_course_group_integrity,
        ),
    ]
