# Generated by Django 6.0.7 on 2026-08-02 01:39

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def materialize_legacy_course_group_activities(apps, schema_editor):
    Cohort = apps.get_model('learning', 'LearningCohort')
    GroupActivity = apps.get_model('learning', 'CourseGroupActivity')
    ActivityProgress = apps.get_model('learning', 'ActivityProgress')
    ActivityProgressEvent = apps.get_model('learning', 'ActivityProgressEvent')
    UnitProgress = apps.get_model('learning', 'UnitProgress')
    EnrollmentCohortAssignment = apps.get_model(
        'learning', 'EnrollmentCohortAssignment'
    )

    Cohort.objects.all().update(migration_review_required=True)
    for cohort in Cohort.objects.select_related('release').iterator():
        snapshot = cohort.release.snapshot
        if not isinstance(snapshot, dict):
            continue
        for module in snapshot.get('modules', []):
            activities = module.get('activities')
            if not isinstance(activities, list):
                activities = [
                    {
                        'id': unit.get('id'),
                        'type': 'lesson',
                        'title': unit.get('title', ''),
                        'summary': unit.get('summary', ''),
                        'position': unit.get('position'),
                        'required': True,
                        'completion_policy': {'method': 'view'},
                        'availability_rules': [],
                    }
                    for unit in module.get('units', [])
                    if isinstance(unit, dict)
                ]
            for activity in activities:
                if not isinstance(activity, dict) or not activity.get('id'):
                    continue
                GroupActivity.objects.create(
                    course_group_id=cohort.id,
                    academic_period_id=cohort.academic_period_id,
                    course_release_id=cohort.release_id,
                    source_activity_id=activity['id'],
                    source_module_id=module['id'],
                    activity_type=activity.get('type', 'lesson'),
                    module_title=module.get('title', ''),
                    title=activity.get('title', ''),
                    summary=activity.get('summary', ''),
                    module_position=module['position'],
                    position=activity['position'],
                    required=activity.get('required', True),
                    completion_policy=activity.get(
                        'completion_policy', {'method': 'view'}
                    ),
                    availability_rules=activity.get('availability_rules', []),
                    release_snapshot_digest=cohort.release.snapshot_digest,
                    migration_review_required=True,
                )

    for unit_progress in UnitProgress.objects.select_related(
        'course_progress__release_assignment__enrollment'
    ).iterator():
        course_progress = unit_progress.course_progress
        assignment = course_progress.release_assignment
        enrollment = assignment.enrollment
        cohort_id = enrollment.cohort_id
        if cohort_id is None:
            cohort_id = (
                EnrollmentCohortAssignment.objects.filter(
                    enrollment_id=enrollment.id,
                    ended_at__isnull=True,
                )
                .values_list('cohort_id', flat=True)
                .first()
            )
        if cohort_id is None:
            continue
        group_activity = GroupActivity.objects.filter(
            course_group_id=cohort_id,
            course_release_id=assignment.release_id,
            source_activity_id=unit_progress.unit_id,
        ).first()
        if group_activity is None:
            continue
        status = (
            'completed' if unit_progress.status == 'completed' else 'in_progress'
        )
        occurred_at = (
            unit_progress.completed_at
            or unit_progress.last_opened_at
            or timezone.now()
        )
        evidence = {'legacy_unit_progress_id': str(unit_progress.id)}
        progress = ActivityProgress.objects.create(
            course_progress_id=course_progress.id,
            group_activity_id=group_activity.id,
            status=status,
            evidence=evidence,
            source='migration',
            policy_version=1,
            started_at=unit_progress.last_opened_at,
            completed_at=unit_progress.completed_at,
            state_changed_at=occurred_at,
        )
        ActivityProgressEvent.objects.create(
            activity_progress_id=progress.id,
            previous_status='',
            new_status=status,
            source='migration',
            policy_version=1,
            evidence=evidence,
            occurred_at=occurred_at,
        )


def reverse_legacy_course_group_activities(apps, schema_editor):
    apps.get_model('learning', 'ActivityProgressEvent').objects.all().delete()
    apps.get_model('learning', 'ActivityProgress').objects.all().delete()
    apps.get_model('learning', 'CourseGroupActivity').objects.all().delete()
    apps.get_model('learning', 'LearningCohort').objects.all().update(
        migration_review_required=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseactivity_courseactivityavailabilityrule_and_more'),
        ('learning', '0006_cohortstaffassignment_enrollmentcohortassignment_and_more'),
        ('organizations', '0007_organization_activated_at_organization_status_and_more'),
        ('publishing', '0002_enforce_release_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Bloqueada'), ('available', 'Disponible'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('passed', 'Aprobada'), ('failed', 'No aprobada'), ('missed', 'No asistida'), ('waived', 'Exenta')], default='available', max_length=16)),
                ('evidence', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('lesson', 'Lección'), ('attendance', 'Asistencia'), ('assessment', 'Evaluación'), ('manual', 'Ajuste manual'), ('migration', 'Migración')], max_length=16)),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('state_changed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityProgressEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('locked', 'Bloqueada'), ('available', 'Disponible'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('passed', 'Aprobada'), ('failed', 'No aprobada'), ('missed', 'No asistida'), ('waived', 'Exenta')], default='', max_length=16)),
                ('new_status', models.CharField(choices=[('locked', 'Bloqueada'), ('available', 'Disponible'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('passed', 'Aprobada'), ('failed', 'No aprobada'), ('missed', 'No asistida'), ('waived', 'Exenta')], max_length=16)),
                ('source', models.CharField(choices=[('lesson', 'Lección'), ('attendance', 'Asistencia'), ('assessment', 'Evaluación'), ('manual', 'Ajuste manual'), ('migration', 'Migración')], max_length=16)),
                ('policy_version', models.PositiveIntegerField()),
                ('evidence', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseGroupActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_activity_id', models.UUIDField()),
                ('source_module_id', models.UUIDField()),
                ('activity_type', models.CharField(choices=[('lesson', 'Lección'), ('live_class', 'Clase en vivo'), ('assessment', 'Evaluación')], max_length=24)),
                ('module_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, max_length=1200)),
                ('module_position', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('completion_policy', models.JSONField(default=dict)),
                ('availability_rules', models.JSONField(blank=True, default=list)),
                ('binding_snapshot', models.JSONField(default=dict)),
                ('release_snapshot_digest', models.CharField(max_length=64)),
                ('migration_review_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('module_position', 'position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='learningcohort',
            name='migration_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningevent',
            name='event_type',
            field=models.CharField(choices=[('enrollment_created', 'Matrícula creada'), ('enrollment_suspended', 'Matrícula suspendida'), ('enrollment_reactivated', 'Matrícula reactivada'), ('enrollment_revoked', 'Matrícula revocada'), ('release_assigned', 'Release asignado'), ('release_upgraded', 'Release actualizado'), ('course_started', 'Curso iniciado'), ('course_completed', 'Curso completado'), ('course_reopened', 'Curso reabierto'), ('unit_opened', 'Unidad abierta'), ('unit_completed', 'Unidad completada'), ('unit_reopened', 'Unidad reabierta'), ('requirement_completed', 'Requisito externo completado'), ('activity_state_changed', 'Estado de actividad actualizado')], max_length=32),
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('period_type', models.CharField(choices=[('school_year', 'Año escolar'), ('term', 'Periodo'), ('semester', 'Semestre'), ('trimester', 'Trimestre'), ('quarter', 'Cuatrimestre'), ('grading_period', 'Periodo de calificación')], max_length=24)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_periods_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_periods', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='learning.academicperiod')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_periods_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_on', 'ends_on', 'name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='learningcohort',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_groups', to='learning.academicperiod'),
        ),
        migrations.AddIndex(
            model_name='learningcohort',
            index=models.Index(fields=['academic_period', 'status'], name='learn_cohort_period_state_ix'),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='course_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_progress', to='learning.courseprogress'),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='state_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_progress_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityprogressevent',
            name='activity_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='learning.activityprogress'),
        ),
        migrations.AddField(
            model_name='activityprogressevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_progress_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegroupactivity',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_group_activities', to='learning.academicperiod'),
        ),
        migrations.AddField(
            model_name='coursegroupactivity',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_instances', to='learning.learningcohort'),
        ),
        migrations.AddField(
            model_name='coursegroupactivity',
            name='course_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_group_activities', to='publishing.courserelease'),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='group_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_progress', to='learning.coursegroupactivity'),
        ),
        migrations.RunPython(
            materialize_legacy_course_group_activities,
            reverse_legacy_course_group_activities,
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['organization', 'starts_on', 'ends_on'], name='learn_period_org_dates_ix'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('organization'), name='learning_period_org_slug_ci'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__lte', models.F('ends_on'))), name='learning_period_date_window'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('id')), _negated=True), _connector='OR'), name='learning_period_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.CheckConstraint(condition=models.Q(('lock_version__gt', 0)), name='learning_period_lock_positive'),
        ),
        migrations.AddIndex(
            model_name='activityprogressevent',
            index=models.Index(fields=['activity_progress', 'occurred_at'], name='learn_activity_event_time_ix'),
        ),
        migrations.AddIndex(
            model_name='coursegroupactivity',
            index=models.Index(fields=['course_group', 'module_position', 'position'], name='learn_group_activity_order_ix'),
        ),
        migrations.AddIndex(
            model_name='coursegroupactivity',
            index=models.Index(fields=['activity_type', 'migration_review_required'], name='learn_group_activity_type_ix'),
        ),
        migrations.AddConstraint(
            model_name='coursegroupactivity',
            constraint=models.UniqueConstraint(fields=('course_group', 'source_activity_id'), name='learn_group_activity_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursegroupactivity',
            constraint=models.UniqueConstraint(fields=('course_group', 'module_position', 'position'), name='learn_group_activity_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursegroupactivity',
            constraint=models.CheckConstraint(condition=models.Q(('module_position__gt', 0), ('position__gt', 0)), name='learn_group_activity_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='coursegroupactivity',
            constraint=models.CheckConstraint(condition=models.Q(('release_snapshot_digest__regex', '^[0-9a-f]{64}$')), name='learn_group_activity_digest_sha256'),
        ),
        migrations.AddIndex(
            model_name='activityprogress',
            index=models.Index(fields=['course_progress', 'status'], name='learn_act_progress_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='activityprogress',
            constraint=models.UniqueConstraint(fields=('course_progress', 'group_activity'), name='learn_activity_progress_unique'),
        ),
        migrations.AddConstraint(
            model_name='activityprogress',
            constraint=models.CheckConstraint(condition=models.Q(('policy_version__gt', 0), ('lock_version__gt', 0)), name='learn_activity_progress_versions_positive'),
        ),
    ]
